/**
 * Hub4Estate Comprehensive Electrical Product Catalog
 *
 * This file contains deeply structured data for:
 * - Categories and Subcategories
 * - Brands with complete information
 * - Products with full specifications
 *
 * Data sourced from major Indian electrical manufacturers' catalogs
 */

// ============================================
// CATEGORIES & SUBCATEGORIES
// ============================================

export const categories = [
  {
    name: 'Wires & Cables',
    slug: 'wires-cables',
    description: 'Copper and aluminum wires and cables for residential, commercial, and industrial applications',
    icon: 'cable',
    sortOrder: 1,
    whatIsIt: 'Electrical wires and cables are conductors used to transmit electrical power from one point to another. They consist of a conductor (copper or aluminum) surrounded by insulation.',
    whereUsed: 'Used throughout the home for power distribution - from the meter to distribution board, and from DB to all electrical points including lights, fans, sockets, and appliances.',
    whyQualityMatters: 'Quality wires prevent electrical fires, reduce power losses, and ensure safe operation for 25+ years. Poor quality wires can overheat, melt insulation, and cause short circuits.',
    commonMistakes: 'Using undersized wires for heavy loads, choosing aluminum over copper for indoor wiring, not using FRLS/HRFR rated wires, and buying uncertified products.',
    subCategories: [
      {
        name: 'House Wiring Cables',
        slug: 'house-wiring',
        description: 'FR, FRLS, and HRFR insulated copper cables for residential wiring',
        productTypes: [
          { name: 'Single Core FR Cables', slug: 'single-core-fr', description: 'Flame Retardant PVC insulated single core copper cables' },
          { name: 'Single Core FRLS Cables', slug: 'single-core-frls', description: 'Flame Retardant Low Smoke cables for enhanced safety' },
          { name: 'Single Core HRFR Cables', slug: 'single-core-hrfr', description: 'Heat Resistant Flame Retardant cables for high temperature areas' },
          { name: 'Multi Core Cables', slug: 'multi-core', description: 'Multiple conductor cables for various applications' },
          { name: 'Flexible Cables', slug: 'flexible', description: 'Highly flexible cables for appliance connections' },
        ]
      },
      {
        name: 'Power Cables',
        slug: 'power-cables',
        description: 'Heavy duty cables for high power transmission',
        productTypes: [
          { name: 'Armoured Cables', slug: 'armoured', description: 'Steel wire armoured cables for underground and outdoor use' },
          { name: 'XLPE Cables', slug: 'xlpe', description: 'Cross-linked polyethylene insulated power cables' },
          { name: 'LT Power Cables', slug: 'lt-power', description: 'Low tension power cables up to 1.1kV' },
        ]
      },
      {
        name: 'Control & Communication Cables',
        slug: 'control-communication',
        description: 'Specialized cables for control and data transmission',
        productTypes: [
          { name: 'LAN Cables', slug: 'lan', description: 'CAT5e and CAT6 network cables' },
          { name: 'CCTV Cables', slug: 'cctv', description: 'Coaxial and 3+1 cables for surveillance systems' },
          { name: 'Telephone Cables', slug: 'telephone', description: 'Communication cables for telecom applications' },
          { name: 'Speaker Cables', slug: 'speaker', description: 'Cables for audio systems' },
        ]
      },
      {
        name: 'Solar Cables',
        slug: 'solar-cables',
        description: 'UV resistant DC cables for solar installations',
        productTypes: [
          { name: 'Solar DC Cables', slug: 'solar-dc', description: 'UV and weather resistant DC cables for solar panels' },
        ]
      }
    ]
  },
  {
    name: 'Switches & Sockets',
    slug: 'switches-sockets',
    description: 'Modular switches, sockets, and wiring accessories for homes and offices',
    icon: 'toggle-right',
    sortOrder: 2,
    whatIsIt: 'Modular switches and sockets are electrical accessories that provide control points for lights and power outlets in a standardized modular format.',
    whereUsed: 'Every room in the house - bedrooms, living rooms, kitchens, bathrooms. Also in offices, hotels, and commercial spaces.',
    whyQualityMatters: 'Quality switches last 100,000+ operations, have better contact materials preventing arcing, and include safety features like child protection.',
    commonMistakes: 'Mixing different brand modules in same frame, overloading sockets, installing outdoor switches without IP rating.',
    subCategories: [
      {
        name: 'Modular Switches',
        slug: 'modular-switches',
        description: 'One-way, two-way, and specialty switches',
        productTypes: [
          { name: 'One Way Switches', slug: 'one-way', description: 'Standard on/off switches for single point control' },
          { name: 'Two Way Switches', slug: 'two-way', description: 'Switches for two-point control (staircase, corridors)' },
          { name: 'Intermediate Switches', slug: 'intermediate', description: 'For multi-point control with two-way switches' },
          { name: 'Bell Push Switches', slug: 'bell-push', description: 'Momentary switches for doorbells' },
          { name: 'Dimmer Switches', slug: 'dimmer', description: 'Variable brightness control for lights' },
          { name: 'Fan Regulators', slug: 'fan-regulator', description: 'Speed control for ceiling fans' },
        ]
      },
      {
        name: 'Sockets & Outlets',
        slug: 'sockets-outlets',
        description: 'Power sockets for various applications',
        productTypes: [
          { name: '6A Sockets', slug: '6a-socket', description: 'For low power devices - phone chargers, lamps' },
          { name: '16A Sockets', slug: '16a-socket', description: 'For high power devices - ACs, geysers' },
          { name: 'Universal Sockets', slug: 'universal', description: 'Multi-pin sockets accepting various plug types' },
          { name: 'USB Sockets', slug: 'usb', description: 'Sockets with built-in USB charging ports' },
          { name: 'Shaver Sockets', slug: 'shaver', description: 'Isolated sockets for bathroom use' },
        ]
      },
      {
        name: 'Plates & Frames',
        slug: 'plates-frames',
        description: 'Cover plates and mounting frames',
        productTypes: [
          { name: 'Cover Plates', slug: 'cover-plates', description: 'Decorative front plates in various finishes' },
          { name: 'Mounting Frames', slug: 'mounting-frames', description: 'Grid frames for modular systems' },
          { name: 'Surface Boxes', slug: 'surface-boxes', description: 'For surface mounting applications' },
          { name: 'Concealed Boxes', slug: 'concealed-boxes', description: 'For flush mounting in walls' },
        ]
      }
    ]
  },
  {
    name: 'MCBs & Distribution',
    slug: 'mcbs-distribution',
    description: 'Circuit protection devices and distribution boards',
    icon: 'shield',
    sortOrder: 3,
    whatIsIt: 'MCBs (Miniature Circuit Breakers) are automatic electrical switches that protect circuits from overload and short circuits. Distribution boards house MCBs and distribute power.',
    whereUsed: 'Distribution boards are typically installed near the meter or at a central location. Every circuit in the house connects through an MCB.',
    whyQualityMatters: 'MCBs are your first line of defense against electrical fires. Quality MCBs trip accurately at rated current and have higher breaking capacity.',
    commonMistakes: 'Using wrong amperage MCBs, not using RCCB for wet areas, overloading circuits, poor DB wiring.',
    subCategories: [
      {
        name: 'MCBs',
        slug: 'mcbs',
        description: 'Miniature Circuit Breakers for overcurrent protection',
        productTypes: [
          { name: 'Single Pole MCBs', slug: 'sp-mcb', description: 'Single phase protection (6A to 63A)' },
          { name: 'Double Pole MCBs', slug: 'dp-mcb', description: 'Single phase with neutral protection' },
          { name: 'Triple Pole MCBs', slug: 'tp-mcb', description: 'Three phase protection' },
          { name: 'Four Pole MCBs', slug: 'fp-mcb', description: 'Three phase with neutral protection' },
          { name: 'DC MCBs', slug: 'dc-mcb', description: 'For DC applications like solar' },
        ]
      },
      {
        name: 'RCCBs & RCBOs',
        slug: 'rccb-rcbo',
        description: 'Earth leakage and combined protection devices',
        productTypes: [
          { name: 'Double Pole RCCB', slug: 'dp-rccb', description: 'Earth leakage protection for single phase' },
          { name: 'Four Pole RCCB', slug: 'fp-rccb', description: 'Earth leakage protection for three phase' },
          { name: 'RCBO', slug: 'rcbo', description: 'Combined MCB and RCCB in one device' },
        ]
      },
      {
        name: 'Distribution Boards',
        slug: 'distribution-boards',
        description: 'Enclosures for MCBs and circuit distribution',
        productTypes: [
          { name: 'SPN Distribution Boards', slug: 'spn-db', description: 'Single phase and neutral DBs (4-way to 12-way)' },
          { name: 'TPN Distribution Boards', slug: 'tpn-db', description: 'Three phase and neutral DBs' },
          { name: 'MCB Boxes', slug: 'mcb-box', description: 'Small enclosures for individual MCBs' },
        ]
      },
      {
        name: 'Isolators & Changeovers',
        slug: 'isolators-changeovers',
        description: 'Manual isolation and changeover switches',
        productTypes: [
          { name: 'Isolator Switches', slug: 'isolator', description: 'Manual isolation switches (32A to 125A)' },
          { name: 'Changeover Switches', slug: 'changeover', description: 'Manual changeover for generator backup' },
          { name: 'Automatic Changeover', slug: 'auto-changeover', description: 'Automatic transfer switches' },
        ]
      }
    ]
  },
  {
    name: 'Lighting',
    slug: 'lighting',
    description: 'LED lights, fixtures, and decorative lighting solutions',
    icon: 'lightbulb',
    sortOrder: 4,
    whatIsIt: 'Modern LED lighting provides energy-efficient illumination with longer lifespan compared to traditional incandescent or CFL bulbs.',
    whereUsed: 'Throughout the home - general lighting, task lighting, accent lighting, and outdoor lighting.',
    whyQualityMatters: 'Quality LEDs provide consistent color temperature, better CRI for true colors, no flickering, and longer lifespan (25,000-50,000 hours).',
    commonMistakes: 'Wrong color temperature for room type, insufficient lumens, poor CRI affecting visibility, not matching driver quality.',
    subCategories: [
      {
        name: 'LED Bulbs',
        slug: 'led-bulbs',
        description: 'Standard LED bulbs in various wattages',
        productTypes: [
          { name: 'LED Bulbs - B22', slug: 'led-bulb-b22', description: 'Bayonet cap LED bulbs (7W to 23W)' },
          { name: 'LED Bulbs - E27', slug: 'led-bulb-e27', description: 'Edison screw LED bulbs' },
          { name: 'LED Bulbs - E14', slug: 'led-bulb-e14', description: 'Small Edison screw for decorative fixtures' },
        ]
      },
      {
        name: 'LED Panel Lights',
        slug: 'led-panels',
        description: 'Surface and recessed panel lights',
        productTypes: [
          { name: 'Round Panel Lights', slug: 'round-panel', description: 'Circular recessed panels (6W to 24W)' },
          { name: 'Square Panel Lights', slug: 'square-panel', description: 'Square recessed panels' },
          { name: 'Surface Panel Lights', slug: 'surface-panel', description: 'Surface mounted panels' },
          { name: '2x2 Panel Lights', slug: '2x2-panel', description: 'Commercial grade ceiling panels' },
        ]
      },
      {
        name: 'Downlights & Spotlights',
        slug: 'downlights-spotlights',
        description: 'Recessed and surface mounted directional lights',
        productTypes: [
          { name: 'LED Downlights', slug: 'downlight', description: 'Recessed ceiling downlights' },
          { name: 'LED Spotlights', slug: 'spotlight', description: 'Adjustable directional lights' },
          { name: 'Track Lights', slug: 'track-light', description: 'Track mounted adjustable lights' },
          { name: 'COB Lights', slug: 'cob-light', description: 'Chip-on-board high intensity lights' },
        ]
      },
      {
        name: 'LED Tube Lights',
        slug: 'led-tubes',
        description: 'LED battens and tube lights',
        productTypes: [
          { name: 'LED Battens', slug: 'led-batten', description: 'Integrated LED tube lights (2ft to 4ft)' },
          { name: 'T5 LED Tubes', slug: 't5-tube', description: 'Slim profile LED tubes' },
          { name: 'T8 LED Tubes', slug: 't8-tube', description: 'Standard retrofit LED tubes' },
        ]
      },
      {
        name: 'Decorative Lights',
        slug: 'decorative-lights',
        description: 'Chandeliers, wall lights, and decorative fixtures',
        productTypes: [
          { name: 'Chandeliers', slug: 'chandelier', description: 'Decorative hanging light fixtures' },
          { name: 'Wall Lights', slug: 'wall-light', description: 'Wall mounted decorative lights' },
          { name: 'Strip Lights', slug: 'strip-light', description: 'Flexible LED strip lighting' },
          { name: 'String Lights', slug: 'string-light', description: 'Decorative string lights' },
        ]
      },
      {
        name: 'Outdoor Lights',
        slug: 'outdoor-lights',
        description: 'Weather resistant outdoor lighting',
        productTypes: [
          { name: 'Flood Lights', slug: 'flood-light', description: 'High power area lighting' },
          { name: 'Garden Lights', slug: 'garden-light', description: 'Landscape and pathway lighting' },
          { name: 'Street Lights', slug: 'street-light', description: 'Pole mounted road lighting' },
          { name: 'Bulkhead Lights', slug: 'bulkhead', description: 'Weather resistant wall lights' },
        ]
      }
    ]
  },
  {
    name: 'Fans & Ventilation',
    slug: 'fans-ventilation',
    description: 'Ceiling fans, exhaust fans, and ventilation solutions',
    icon: 'fan',
    sortOrder: 5,
    whatIsIt: 'Ceiling fans provide air circulation for cooling comfort, while exhaust fans remove stale air, moisture, and odors from enclosed spaces.',
    whereUsed: 'Ceiling fans in bedrooms, living rooms, halls. Exhaust fans in kitchens, bathrooms, and utility areas.',
    whyQualityMatters: 'Quality fans are quieter, more efficient (BLDC technology saves 50%), more durable, and have better air delivery.',
    commonMistakes: 'Wrong sweep size for room, ignoring BEE rating, poor installation causing wobble, not using exhaust fans in wet areas.',
    subCategories: [
      {
        name: 'Ceiling Fans',
        slug: 'ceiling-fans',
        description: 'Standard and decorative ceiling fans',
        productTypes: [
          { name: 'Standard Ceiling Fans', slug: 'standard-fan', description: 'Conventional induction motor fans' },
          { name: 'BLDC Ceiling Fans', slug: 'bldc-fan', description: 'Energy efficient brushless DC motor fans' },
          { name: 'Decorative Fans', slug: 'decorative-fan', description: 'Designer and premium ceiling fans' },
          { name: 'Industrial Fans', slug: 'industrial-fan', description: 'Heavy duty high volume fans' },
          { name: 'Fans with Lights', slug: 'fan-with-light', description: 'Ceiling fans with integrated lighting' },
        ]
      },
      {
        name: 'Exhaust Fans',
        slug: 'exhaust-fans',
        description: 'Kitchen, bathroom, and industrial exhaust fans',
        productTypes: [
          { name: 'Domestic Exhaust Fans', slug: 'domestic-exhaust', description: 'For homes and small spaces (6" to 12")' },
          { name: 'Kitchen Exhaust Fans', slug: 'kitchen-exhaust', description: 'Heavy duty kitchen ventilation' },
          { name: 'Industrial Exhaust Fans', slug: 'industrial-exhaust', description: 'High capacity industrial ventilation' },
        ]
      },
      {
        name: 'Table & Pedestal Fans',
        slug: 'table-pedestal',
        description: 'Portable fans for personal cooling',
        productTypes: [
          { name: 'Table Fans', slug: 'table-fan', description: 'Compact desk-mounted fans' },
          { name: 'Pedestal Fans', slug: 'pedestal-fan', description: 'Height adjustable floor fans' },
          { name: 'Wall Fans', slug: 'wall-fan', description: 'Wall mounted fans' },
        ]
      }
    ]
  },
  {
    name: 'Water Heaters',
    slug: 'water-heaters',
    description: 'Geysers and water heating solutions',
    icon: 'thermometer',
    sortOrder: 6,
    whatIsIt: 'Electric water heaters (geysers) heat water for bathing and other purposes. Available as storage (tank) or instant (tankless) types.',
    whereUsed: 'Bathrooms, kitchens, and utility areas where hot water is needed.',
    whyQualityMatters: 'Quality geysers have better insulation (less heat loss), safer heating elements, longer tank life, and proper safety features.',
    commonMistakes: 'Wrong capacity for family size, no MCB protection, no pressure relief valve, poor installation.',
    subCategories: [
      {
        name: 'Storage Water Heaters',
        slug: 'storage-geysers',
        description: 'Tank-based water heaters',
        productTypes: [
          { name: 'Vertical Geysers', slug: 'vertical-geyser', description: 'Standard wall mounted storage geysers (6L to 35L)' },
          { name: 'Horizontal Geysers', slug: 'horizontal-geyser', description: 'Space saving horizontal mounting' },
        ]
      },
      {
        name: 'Instant Water Heaters',
        slug: 'instant-geysers',
        description: 'Tankless on-demand water heaters',
        productTypes: [
          { name: 'Instant Geysers', slug: 'instant-geyser', description: 'Quick heating tankless geysers (1L to 3L)' },
        ]
      },
      {
        name: 'Solar Water Heaters',
        slug: 'solar-water-heaters',
        description: 'Solar powered water heating systems',
        productTypes: [
          { name: 'Flat Plate Collectors', slug: 'flat-plate', description: 'Standard solar water heaters' },
          { name: 'Evacuated Tube Collectors', slug: 'etc', description: 'High efficiency tube collectors' },
        ]
      }
    ]
  },
  {
    name: 'Earthing & Safety',
    slug: 'earthing-safety',
    description: 'Earthing equipment and safety devices',
    icon: 'shield-check',
    sortOrder: 7,
    whatIsIt: 'Earthing provides a safe path for fault currents to flow to ground, protecting people from electric shock and equipment from damage.',
    whereUsed: 'Every electrical installation requires proper earthing. Main earth near meter, equipment earth for appliances.',
    whyQualityMatters: 'Proper earthing is critical for safety. Poor earthing can result in electric shocks, equipment damage, and fire hazards.',
    commonMistakes: 'Using pipe as earth, not maintaining earth pit, poor connections, not testing earth resistance.',
    subCategories: [
      {
        name: 'Earthing Equipment',
        slug: 'earthing-equipment',
        description: 'Earth electrodes and accessories',
        productTypes: [
          { name: 'Earth Rods', slug: 'earth-rod', description: 'Copper bonded and GI earth rods' },
          { name: 'Earth Plates', slug: 'earth-plate', description: 'Copper and GI earth plates' },
          { name: 'Earth Pits', slug: 'earth-pit', description: 'Complete earth pit chambers' },
          { name: 'Earthing Compounds', slug: 'earth-compound', description: 'Soil treatment compounds' },
        ]
      },
      {
        name: 'Surge Protection',
        slug: 'surge-protection',
        description: 'Surge protectors and SPDs',
        productTypes: [
          { name: 'Type 1 SPD', slug: 'spd-type1', description: 'Lightning surge protection' },
          { name: 'Type 2 SPD', slug: 'spd-type2', description: 'Surge protection for distribution boards' },
          { name: 'Type 3 SPD', slug: 'spd-type3', description: 'Point of use surge protection' },
          { name: 'Spike Guards', slug: 'spike-guard', description: 'Multi-socket surge protectors' },
        ]
      }
    ]
  },
  {
    name: 'Smart & Automation',
    slug: 'smart-automation',
    description: 'Smart home devices and automation solutions',
    icon: 'smartphone',
    sortOrder: 8,
    whatIsIt: 'Smart home devices allow remote control and automation of electrical equipment through smartphones, voice commands, or sensors.',
    whereUsed: 'Any electrical point that needs remote or automated control - lights, fans, ACs, geysers, etc.',
    whyQualityMatters: 'Quality smart devices have better connectivity, stronger security, and reliable operation.',
    commonMistakes: 'Incompatible ecosystems, poor WiFi coverage, not considering load ratings.',
    subCategories: [
      {
        name: 'Smart Switches',
        slug: 'smart-switches',
        description: 'WiFi and Bluetooth enabled switches',
        productTypes: [
          { name: 'Smart Touch Switches', slug: 'smart-touch', description: 'Touch panel smart switches' },
          { name: 'Smart Retrofit Modules', slug: 'smart-retrofit', description: 'Add-on modules for existing switches' },
          { name: 'Smart Fan Controllers', slug: 'smart-fan-controller', description: 'WiFi fan speed controllers' },
        ]
      },
      {
        name: 'Smart Lighting',
        slug: 'smart-lighting',
        description: 'Smart bulbs and lighting controls',
        productTypes: [
          { name: 'Smart LED Bulbs', slug: 'smart-bulb', description: 'WiFi/Bluetooth controlled LED bulbs' },
          { name: 'Smart LED Strips', slug: 'smart-strip', description: 'Color changing smart strips' },
        ]
      },
      {
        name: 'Sensors & Controllers',
        slug: 'sensors-controllers',
        description: 'Motion sensors and smart controllers',
        productTypes: [
          { name: 'Motion Sensors', slug: 'motion-sensor', description: 'PIR motion detection sensors' },
          { name: 'Door Sensors', slug: 'door-sensor', description: 'Door/window open sensors' },
          { name: 'Smart Plugs', slug: 'smart-plug', description: 'WiFi controlled plug sockets' },
        ]
      }
    ]
  },
  {
    name: 'Doorbells & Accessories',
    slug: 'doorbells-accessories',
    description: 'Doorbells, video door phones, and accessories',
    icon: 'bell',
    sortOrder: 9,
    whatIsIt: 'Doorbells alert residents to visitors. Modern video door phones allow seeing and communicating with visitors remotely.',
    whereUsed: 'Main entrance door, gates, and secondary entrances.',
    whyQualityMatters: 'Quality doorbells have better sound, longer range, and video door phones provide security.',
    commonMistakes: 'Poor placement, weak WiFi for smart doorbells, not considering weather protection.',
    subCategories: [
      {
        name: 'Doorbells',
        slug: 'doorbells',
        description: 'Wired and wireless doorbells',
        productTypes: [
          { name: 'Wired Doorbells', slug: 'wired-doorbell', description: 'Traditional wired ding-dong bells' },
          { name: 'Wireless Doorbells', slug: 'wireless-doorbell', description: 'Battery operated wireless bells' },
          { name: 'Smart Doorbells', slug: 'smart-doorbell', description: 'WiFi enabled video doorbells' },
        ]
      },
      {
        name: 'Video Door Phones',
        slug: 'video-door-phones',
        description: 'Intercom systems with video',
        productTypes: [
          { name: 'Wired Video Door Phone', slug: 'wired-vdp', description: 'Hardwired video intercom systems' },
          { name: 'Wireless Video Door Phone', slug: 'wireless-vdp', description: 'WiFi video door phones' },
        ]
      }
    ]
  },
  {
    name: 'Conduits & Accessories',
    slug: 'conduits-accessories',
    description: 'PVC conduits, boxes, and wiring accessories',
    icon: 'circle-dot',
    sortOrder: 10,
    whatIsIt: 'Conduits are tubes that protect electrical wires and provide organized cable management in walls and ceilings.',
    whereUsed: 'Inside walls and ceilings to route electrical wires safely and allow future maintenance.',
    whyQualityMatters: 'Quality conduits are flame retardant, durable, and allow easy wire pulling.',
    commonMistakes: 'Using undersized conduits, not using bends properly, damaging during construction.',
    subCategories: [
      {
        name: 'PVC Conduits',
        slug: 'pvc-conduits',
        description: 'PVC pipes for electrical wiring',
        productTypes: [
          { name: 'Rigid PVC Conduits', slug: 'rigid-conduit', description: 'Standard rigid conduit pipes' },
          { name: 'Flexible PVC Conduits', slug: 'flexible-conduit', description: 'Corrugated flexible conduits' },
        ]
      },
      {
        name: 'Conduit Accessories',
        slug: 'conduit-accessories',
        description: 'Fittings and accessories',
        productTypes: [
          { name: 'Junction Boxes', slug: 'junction-box', description: 'Wire connection enclosures' },
          { name: 'Conduit Bends', slug: 'conduit-bend', description: 'Pre-formed conduit bends' },
          { name: 'Conduit Couplers', slug: 'conduit-coupler', description: 'Conduit joining accessories' },
        ]
      }
    ]
  },
  {
    name: 'Tools & Testers',
    slug: 'tools-testers',
    description: 'Electrical testing and installation tools',
    icon: 'wrench',
    sortOrder: 11,
    whatIsIt: 'Specialized tools for electrical work including testers, meters, and installation tools.',
    whereUsed: 'For installation, testing, and maintenance of electrical systems.',
    whyQualityMatters: 'Quality tools ensure safety, accuracy, and durability.',
    commonMistakes: 'Using damaged tools, not calibrating meters, ignoring safety ratings.',
    subCategories: [
      {
        name: 'Testing Equipment',
        slug: 'testing-equipment',
        description: 'Electrical testing devices',
        productTypes: [
          { name: 'Multimeters', slug: 'multimeter', description: 'Digital and analog multimeters' },
          { name: 'Voltage Testers', slug: 'voltage-tester', description: 'Non-contact voltage detectors' },
          { name: 'Clamp Meters', slug: 'clamp-meter', description: 'AC/DC current clamp meters' },
          { name: 'Earth Testers', slug: 'earth-tester', description: 'Earth resistance measurement' },
          { name: 'Insulation Testers', slug: 'insulation-tester', description: 'Meggers for insulation testing' },
        ]
      },
      {
        name: 'Hand Tools',
        slug: 'hand-tools',
        description: 'Electrical hand tools',
        productTypes: [
          { name: 'Wire Strippers', slug: 'wire-stripper', description: 'Insulation stripping tools' },
          { name: 'Crimping Tools', slug: 'crimping-tool', description: 'Terminal crimping tools' },
          { name: 'Screwdrivers', slug: 'screwdriver', description: 'Insulated screwdriver sets' },
          { name: 'Pliers', slug: 'pliers', description: 'Cutting and holding pliers' },
        ]
      }
    ]
  },
  {
    name: 'Power Backup & Solar',
    slug: 'power-backup-solar',
    description: 'Inverters, UPS, batteries, and solar systems',
    icon: 'sun',
    sortOrder: 12,
    whatIsIt: 'Power backup systems provide electricity during grid outages. Solar systems generate clean energy from sunlight.',
    whereUsed: 'Homes for essential loads during power cuts. Solar for energy independence.',
    whyQualityMatters: 'Quality inverters have better efficiency, pure sine wave output, and longer battery life.',
    commonMistakes: 'Undersized systems, poor battery maintenance, wrong solar panel orientation.',
    subCategories: [
      {
        name: 'Inverters',
        slug: 'inverters',
        description: 'Home UPS and inverters',
        productTypes: [
          { name: 'Home UPS', slug: 'home-ups', description: 'Sine wave inverters for homes' },
          { name: 'Solar Inverters', slug: 'solar-inverter', description: 'Grid-tie and off-grid solar inverters' },
        ]
      },
      {
        name: 'Batteries',
        slug: 'batteries',
        description: 'Inverter and solar batteries',
        productTypes: [
          { name: 'Tubular Batteries', slug: 'tubular-battery', description: 'Deep cycle tubular batteries' },
          { name: 'Lithium Batteries', slug: 'lithium-battery', description: 'Lithium-ion battery packs' },
        ]
      },
      {
        name: 'Solar Panels',
        slug: 'solar-panels',
        description: 'Photovoltaic solar panels',
        productTypes: [
          { name: 'Monocrystalline Panels', slug: 'mono-panel', description: 'High efficiency mono panels' },
          { name: 'Polycrystalline Panels', slug: 'poly-panel', description: 'Standard poly solar panels' },
        ]
      }
    ]
  }
];

// ============================================
// BRANDS
// ============================================

export const brands = [
  // Premium Brands
  {
    name: 'Havells',
    slug: 'havells',
    description: 'Leading Indian electrical equipment company with comprehensive range of wires, switches, MCBs, fans, and lighting',
    website: 'https://havells.com',
    logo: '/brands/havells.png',
    isPremium: true,
    priceSegment: 'Premium',
    qualityRating: 4.5,
  },
  {
    name: 'Legrand',
    slug: 'legrand',
    description: 'French multinational specializing in electrical and digital building infrastructure',
    website: 'https://legrand.co.in',
    logo: '/brands/legrand.png',
    isPremium: true,
    priceSegment: 'Premium',
    qualityRating: 4.7,
  },
  {
    name: 'Schneider Electric',
    slug: 'schneider',
    description: 'Global specialist in energy management and automation with premium switches and MCBs',
    website: 'https://www.se.com/in',
    logo: '/brands/schneider.png',
    isPremium: true,
    priceSegment: 'Premium',
    qualityRating: 4.8,
  },
  {
    name: 'ABB',
    slug: 'abb',
    description: 'Swiss-Swedish multinational known for high-quality switchgear and automation',
    website: 'https://new.abb.com/in',
    logo: '/brands/abb.png',
    isPremium: true,
    priceSegment: 'Premium',
    qualityRating: 4.8,
  },
  {
    name: 'Siemens',
    slug: 'siemens',
    description: 'German multinational with premium switchgear and automation solutions',
    website: 'https://www.siemens.com/in',
    logo: '/brands/siemens.png',
    isPremium: true,
    priceSegment: 'Premium',
    qualityRating: 4.7,
  },

  // Mid-Range Brands
  {
    name: 'Polycab',
    slug: 'polycab',
    description: 'Indias largest manufacturer of wires and cables, also offering switches, fans, and lighting',
    website: 'https://polycab.com',
    logo: '/brands/polycab.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.3,
  },
  {
    name: 'Anchor by Panasonic',
    slug: 'anchor',
    description: 'Trusted brand for switches and wiring accessories, now part of Panasonic',
    website: 'https://anchor.panasonic.co.in',
    logo: '/brands/anchor.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.2,
  },
  {
    name: 'Crompton',
    slug: 'crompton',
    description: 'Heritage brand known for ceiling fans, lighting, and pumps',
    website: 'https://www.crompton.co.in',
    logo: '/brands/crompton.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.2,
  },
  {
    name: 'Orient Electric',
    slug: 'orient',
    description: 'Leading manufacturer of fans, lighting, and home appliances',
    website: 'https://www.orientelectric.com',
    logo: '/brands/orient.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.1,
  },
  {
    name: 'Philips',
    slug: 'philips',
    description: 'Dutch multinational known globally for lighting solutions',
    website: 'https://www.lighting.philips.co.in',
    logo: '/brands/philips.png',
    isPremium: true,
    priceSegment: 'Mid-range',
    qualityRating: 4.4,
  },
  {
    name: 'Finolex',
    slug: 'finolex',
    description: 'Largest manufacturer of electrical and communication cables in India',
    website: 'https://www.finolex.com',
    logo: '/brands/finolex.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.3,
  },
  {
    name: 'KEI Industries',
    slug: 'kei',
    description: 'Major manufacturer of wires, cables, and stainless steel wires',
    website: 'https://www.kei-ind.com',
    logo: '/brands/kei.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.2,
  },
  {
    name: 'Syska',
    slug: 'syska',
    description: 'Leading LED lighting brand in India with wide range of products',
    website: 'https://www.syska.co.in',
    logo: '/brands/syska.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.0,
  },
  {
    name: 'Wipro Lighting',
    slug: 'wipro',
    description: 'Comprehensive lighting solutions from Wipro Consumer Care',
    website: 'https://www.wiprolighting.com',
    logo: '/brands/wipro.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.1,
  },
  {
    name: 'Bajaj Electricals',
    slug: 'bajaj',
    description: 'Diversified electrical equipment company with fans, lighting, and appliances',
    website: 'https://www.bajajelectricals.com',
    logo: '/brands/bajaj.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.0,
  },
  {
    name: 'Atomberg',
    slug: 'atomberg',
    description: 'Innovative BLDC fan manufacturer known for energy efficiency',
    website: 'https://atomberg.com',
    logo: '/brands/atomberg.png',
    isPremium: true,
    priceSegment: 'Premium',
    qualityRating: 4.5,
  },
  {
    name: 'Luminous',
    slug: 'luminous',
    description: 'Leading power backup and solar solutions provider',
    website: 'https://www.luminousindia.com',
    logo: '/brands/luminous.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.2,
  },
  {
    name: 'Microtek',
    slug: 'microtek',
    description: 'Major manufacturer of inverters and UPS systems',
    website: 'https://www.microtekdirect.com',
    logo: '/brands/microtek.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.0,
  },
  {
    name: 'V-Guard',
    slug: 'vguard',
    description: 'South Indian brand known for stabilizers, pumps, and water heaters',
    website: 'https://www.vguard.in',
    logo: '/brands/vguard.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.1,
  },
  {
    name: 'Exide',
    slug: 'exide',
    description: 'Indias largest storage battery company',
    website: 'https://www.exideindustries.com',
    logo: '/brands/exide.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.3,
  },
  {
    name: 'Amaron',
    slug: 'amaron',
    description: 'Premium battery brand from Amara Raja Group',
    website: 'https://www.amaron.in',
    logo: '/brands/amaron.png',
    isPremium: true,
    priceSegment: 'Premium',
    qualityRating: 4.4,
  },

  // Budget Brands
  {
    name: 'GM Modular',
    slug: 'gm-modular',
    description: 'Value-for-money modular switches and electrical accessories',
    website: 'https://www.gmmodular.com',
    logo: '/brands/gm.png',
    isPremium: false,
    priceSegment: 'Budget',
    qualityRating: 3.8,
  },
  {
    name: 'Goldmedal',
    slug: 'goldmedal',
    description: 'Popular brand for switches and wiring accessories',
    website: 'https://www.goldmedalindia.com',
    logo: '/brands/goldmedal.png',
    isPremium: false,
    priceSegment: 'Budget',
    qualityRating: 3.9,
  },
  {
    name: 'RR Kabel',
    slug: 'rr-kabel',
    description: 'Established wire and cable manufacturer',
    website: 'https://www.rrkabel.com',
    logo: '/brands/rrkabel.png',
    isPremium: false,
    priceSegment: 'Budget',
    qualityRating: 4.0,
  },
  {
    name: 'Eveready',
    slug: 'eveready',
    description: 'Known for batteries and LED lighting products',
    website: 'https://www.evereadyindustries.com',
    logo: '/brands/eveready.png',
    isPremium: false,
    priceSegment: 'Budget',
    qualityRating: 3.7,
  },
  {
    name: 'Surya Roshni',
    slug: 'surya',
    description: 'Lighting and steel pipes manufacturer',
    website: 'https://www.surya.co.in',
    logo: '/brands/surya.png',
    isPremium: false,
    priceSegment: 'Budget',
    qualityRating: 3.8,
  },
  {
    name: 'Usha',
    slug: 'usha',
    description: 'Legacy brand for fans and home appliances',
    website: 'https://www.usha.com',
    logo: '/brands/usha.png',
    isPremium: false,
    priceSegment: 'Budget',
    qualityRating: 3.9,
  },
  {
    name: 'Indo Asian',
    slug: 'indo-asian',
    description: 'Switchgear and electrical accessories manufacturer',
    website: 'https://www.indoasian.com',
    logo: '/brands/indoasian.png',
    isPremium: false,
    priceSegment: 'Budget',
    qualityRating: 3.7,
  },
  {
    name: 'C&S Electric',
    slug: 'cs-electric',
    description: 'Switchgear specialist with comprehensive product range',
    website: 'https://www.cselectric.co.in',
    logo: '/brands/cs.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.0,
  },
  {
    name: 'L&T Electrical',
    slug: 'lnt',
    description: 'Industrial switchgear and automation from L&T',
    website: 'https://www.larsentoubro.com',
    logo: '/brands/lnt.png',
    isPremium: true,
    priceSegment: 'Premium',
    qualityRating: 4.6,
  },
  {
    name: 'Tata Power Solar',
    slug: 'tata-solar',
    description: 'Leading solar solutions provider from Tata Group',
    website: 'https://www.tatapowersolar.com',
    logo: '/brands/tatasolar.png',
    isPremium: true,
    priceSegment: 'Premium',
    qualityRating: 4.5,
  },
  {
    name: 'Waaree',
    slug: 'waaree',
    description: 'Indias largest solar panel manufacturer',
    website: 'https://www.waaree.com',
    logo: '/brands/waaree.png',
    isPremium: false,
    priceSegment: 'Mid-range',
    qualityRating: 4.2,
  },
  {
    name: 'Livguard',
    slug: 'livguard',
    description: 'Batteries, inverters, and solar solutions',
    website: 'https://www.livguard.com',
    logo: '/brands/livguard.png',
    isPremium: false,
    priceSegment: 'Budget',
    qualityRating: 3.8,
  },
];

// ============================================
// PRODUCTS - Comprehensive listing with specs
// ============================================

export const products = [
  // ========== WIRES & CABLES ==========
  // Havells House Wiring
  {
    brand: 'havells',
    productType: 'single-core-fr',
    name: 'Havells Life Line Plus S3 HRFR Cable 1.0 sq mm',
    modelNumber: 'WHRFFDNA11X0',
    sku: 'HAV-LLP-1.0-R',
    description: 'Heat Resistant Flame Retardant (HRFR) single core copper cable for house wiring. IS 694 compliant.',
    specifications: JSON.stringify({
      conductorSize: '1.0 sq mm',
      conductorType: 'Electrolytic grade copper',
      insulation: 'HRFR PVC',
      voltage: '1100V',
      currentRating: '11A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
      temperature: '-15°C to 70°C',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/havells-llp-1.0.jpg'],
  },
  {
    brand: 'havells',
    productType: 'single-core-fr',
    name: 'Havells Life Line Plus S3 HRFR Cable 1.5 sq mm',
    modelNumber: 'WHRFFDNA11X5',
    sku: 'HAV-LLP-1.5-R',
    description: 'Heat Resistant Flame Retardant (HRFR) single core copper cable for light and fan circuits.',
    specifications: JSON.stringify({
      conductorSize: '1.5 sq mm',
      conductorType: 'Electrolytic grade copper',
      insulation: 'HRFR PVC',
      voltage: '1100V',
      currentRating: '15A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
      temperature: '-15°C to 70°C',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/havells-llp-1.5.jpg'],
  },
  {
    brand: 'havells',
    productType: 'single-core-fr',
    name: 'Havells Life Line Plus S3 HRFR Cable 2.5 sq mm',
    modelNumber: 'WHRFFDNA12X5',
    sku: 'HAV-LLP-2.5-R',
    description: 'Heat Resistant Flame Retardant (HRFR) single core copper cable for power sockets and medium loads.',
    specifications: JSON.stringify({
      conductorSize: '2.5 sq mm',
      conductorType: 'Electrolytic grade copper',
      insulation: 'HRFR PVC',
      voltage: '1100V',
      currentRating: '20A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
      temperature: '-15°C to 70°C',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/havells-llp-2.5.jpg'],
  },
  {
    brand: 'havells',
    productType: 'single-core-fr',
    name: 'Havells Life Line Plus S3 HRFR Cable 4.0 sq mm',
    modelNumber: 'WHRFFDNA14X0',
    sku: 'HAV-LLP-4.0-R',
    description: 'Heat Resistant Flame Retardant (HRFR) single core copper cable for AC and geyser circuits.',
    specifications: JSON.stringify({
      conductorSize: '4.0 sq mm',
      conductorType: 'Electrolytic grade copper',
      insulation: 'HRFR PVC',
      voltage: '1100V',
      currentRating: '27A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
      temperature: '-15°C to 70°C',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/havells-llp-4.0.jpg'],
  },
  {
    brand: 'havells',
    productType: 'single-core-fr',
    name: 'Havells Life Line Plus S3 HRFR Cable 6.0 sq mm',
    modelNumber: 'WHRFFDNA16X0',
    sku: 'HAV-LLP-6.0-R',
    description: 'Heat Resistant Flame Retardant (HRFR) single core copper cable for main distribution.',
    specifications: JSON.stringify({
      conductorSize: '6.0 sq mm',
      conductorType: 'Electrolytic grade copper',
      insulation: 'HRFR PVC',
      voltage: '1100V',
      currentRating: '36A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
      temperature: '-15°C to 70°C',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/havells-llp-6.0.jpg'],
  },

  // Polycab House Wiring
  {
    brand: 'polycab',
    productType: 'single-core-fr',
    name: 'Polycab Optima Plus FR-LSH Cable 1.0 sq mm',
    modelNumber: 'PLOPT1X0FR',
    sku: 'POL-OPT-1.0-R',
    description: 'Flame Retardant Low Smoke Halogen Free single core copper cable.',
    specifications: JSON.stringify({
      conductorSize: '1.0 sq mm',
      conductorType: '99.97% pure copper',
      insulation: 'FR-LSH PVC',
      voltage: '1100V',
      currentRating: '11A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/polycab-optima-1.0.jpg'],
  },
  {
    brand: 'polycab',
    productType: 'single-core-fr',
    name: 'Polycab Optima Plus FR-LSH Cable 1.5 sq mm',
    modelNumber: 'PLOPT1X5FR',
    sku: 'POL-OPT-1.5-R',
    description: 'Flame Retardant Low Smoke Halogen Free single core copper cable.',
    specifications: JSON.stringify({
      conductorSize: '1.5 sq mm',
      conductorType: '99.97% pure copper',
      insulation: 'FR-LSH PVC',
      voltage: '1100V',
      currentRating: '15A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/polycab-optima-1.5.jpg'],
  },
  {
    brand: 'polycab',
    productType: 'single-core-fr',
    name: 'Polycab Optima Plus FR-LSH Cable 2.5 sq mm',
    modelNumber: 'PLOPT2X5FR',
    sku: 'POL-OPT-2.5-R',
    description: 'Flame Retardant Low Smoke Halogen Free single core copper cable.',
    specifications: JSON.stringify({
      conductorSize: '2.5 sq mm',
      conductorType: '99.97% pure copper',
      insulation: 'FR-LSH PVC',
      voltage: '1100V',
      currentRating: '21A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/polycab-optima-2.5.jpg'],
  },
  {
    brand: 'polycab',
    productType: 'single-core-fr',
    name: 'Polycab Optima Plus FR-LSH Cable 4.0 sq mm',
    modelNumber: 'PLOPT4X0FR',
    sku: 'POL-OPT-4.0-R',
    description: 'Flame Retardant Low Smoke Halogen Free single core copper cable.',
    specifications: JSON.stringify({
      conductorSize: '4.0 sq mm',
      conductorType: '99.97% pure copper',
      insulation: 'FR-LSH PVC',
      voltage: '1100V',
      currentRating: '28A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/polycab-optima-4.0.jpg'],
  },

  // Finolex Cables
  {
    brand: 'finolex',
    productType: 'single-core-fr',
    name: 'Finolex FR PVC Cable 1.0 sq mm',
    modelNumber: 'FIN-FR-1.0',
    sku: 'FIN-FR-1.0-R',
    description: 'Flame Retardant PVC insulated single core copper cable.',
    specifications: JSON.stringify({
      conductorSize: '1.0 sq mm',
      conductorType: 'Annealed bare copper',
      insulation: 'FR PVC',
      voltage: '1100V',
      currentRating: '11A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/finolex-fr-1.0.jpg'],
  },
  {
    brand: 'finolex',
    productType: 'single-core-fr',
    name: 'Finolex FR PVC Cable 1.5 sq mm',
    modelNumber: 'FIN-FR-1.5',
    sku: 'FIN-FR-1.5-R',
    description: 'Flame Retardant PVC insulated single core copper cable.',
    specifications: JSON.stringify({
      conductorSize: '1.5 sq mm',
      conductorType: 'Annealed bare copper',
      insulation: 'FR PVC',
      voltage: '1100V',
      currentRating: '15A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/finolex-fr-1.5.jpg'],
  },
  {
    brand: 'finolex',
    productType: 'single-core-fr',
    name: 'Finolex FR PVC Cable 2.5 sq mm',
    modelNumber: 'FIN-FR-2.5',
    sku: 'FIN-FR-2.5-R',
    description: 'Flame Retardant PVC insulated single core copper cable.',
    specifications: JSON.stringify({
      conductorSize: '2.5 sq mm',
      conductorType: 'Annealed bare copper',
      insulation: 'FR PVC',
      voltage: '1100V',
      currentRating: '21A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/finolex-fr-2.5.jpg'],
  },
  {
    brand: 'finolex',
    productType: 'single-core-fr',
    name: 'Finolex FR PVC Cable 4.0 sq mm',
    modelNumber: 'FIN-FR-4.0',
    sku: 'FIN-FR-4.0-R',
    description: 'Flame Retardant PVC insulated single core copper cable.',
    specifications: JSON.stringify({
      conductorSize: '4.0 sq mm',
      conductorType: 'Annealed bare copper',
      insulation: 'FR PVC',
      voltage: '1100V',
      currentRating: '28A',
      color: ['Red', 'Yellow', 'Blue', 'Black', 'Green'],
      packSize: '90m coil',
      standard: 'IS 694',
    }),
    certifications: ['ISI', 'BIS'],
    warrantyYears: 10,
    images: ['/products/finolex-fr-4.0.jpg'],
  },

  // ========== MCBs ==========
  // Havells MCBs
  {
    brand: 'havells',
    productType: 'sp-mcb',
    name: 'Havells Euro II 6A Single Pole MCB C Curve',
    modelNumber: 'DHMGCSPF006',
    sku: 'HAV-MCB-SP-6A-C',
    description: 'Single pole MCB with 10kA breaking capacity. C curve for general purpose loads.',
    specifications: JSON.stringify({
      poles: 1,
      rating: '6A',
      curve: 'C',
      breakingCapacity: '10kA',
      voltage: '240V AC',
      width: '17.5mm (1 module)',
      standard: 'IS/IEC 60898',
      thermalRelease: '1.13-1.45 In',
      magneticRelease: '5-10 In',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/havells-mcb-sp-6a.jpg'],
  },
  {
    brand: 'havells',
    productType: 'sp-mcb',
    name: 'Havells Euro II 10A Single Pole MCB C Curve',
    modelNumber: 'DHMGCSPF010',
    sku: 'HAV-MCB-SP-10A-C',
    description: 'Single pole MCB with 10kA breaking capacity. Ideal for lighting circuits.',
    specifications: JSON.stringify({
      poles: 1,
      rating: '10A',
      curve: 'C',
      breakingCapacity: '10kA',
      voltage: '240V AC',
      width: '17.5mm (1 module)',
      standard: 'IS/IEC 60898',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/havells-mcb-sp-10a.jpg'],
  },
  {
    brand: 'havells',
    productType: 'sp-mcb',
    name: 'Havells Euro II 16A Single Pole MCB C Curve',
    modelNumber: 'DHMGCSPF016',
    sku: 'HAV-MCB-SP-16A-C',
    description: 'Single pole MCB with 10kA breaking capacity. For fan and light circuits.',
    specifications: JSON.stringify({
      poles: 1,
      rating: '16A',
      curve: 'C',
      breakingCapacity: '10kA',
      voltage: '240V AC',
      width: '17.5mm (1 module)',
      standard: 'IS/IEC 60898',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/havells-mcb-sp-16a.jpg'],
  },
  {
    brand: 'havells',
    productType: 'sp-mcb',
    name: 'Havells Euro II 20A Single Pole MCB C Curve',
    modelNumber: 'DHMGCSPF020',
    sku: 'HAV-MCB-SP-20A-C',
    description: 'Single pole MCB with 10kA breaking capacity. For socket circuits.',
    specifications: JSON.stringify({
      poles: 1,
      rating: '20A',
      curve: 'C',
      breakingCapacity: '10kA',
      voltage: '240V AC',
      width: '17.5mm (1 module)',
      standard: 'IS/IEC 60898',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/havells-mcb-sp-20a.jpg'],
  },
  {
    brand: 'havells',
    productType: 'sp-mcb',
    name: 'Havells Euro II 32A Single Pole MCB C Curve',
    modelNumber: 'DHMGCSPF032',
    sku: 'HAV-MCB-SP-32A-C',
    description: 'Single pole MCB with 10kA breaking capacity. For AC and geyser circuits.',
    specifications: JSON.stringify({
      poles: 1,
      rating: '32A',
      curve: 'C',
      breakingCapacity: '10kA',
      voltage: '240V AC',
      width: '17.5mm (1 module)',
      standard: 'IS/IEC 60898',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/havells-mcb-sp-32a.jpg'],
  },
  {
    brand: 'havells',
    productType: 'dp-mcb',
    name: 'Havells Euro II 32A Double Pole MCB C Curve',
    modelNumber: 'DHMGCDPF032',
    sku: 'HAV-MCB-DP-32A-C',
    description: 'Double pole MCB with 10kA breaking capacity for main isolation.',
    specifications: JSON.stringify({
      poles: 2,
      rating: '32A',
      curve: 'C',
      breakingCapacity: '10kA',
      voltage: '240V AC',
      width: '35mm (2 modules)',
      standard: 'IS/IEC 60898',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/havells-mcb-dp-32a.jpg'],
  },
  {
    brand: 'havells',
    productType: 'dp-mcb',
    name: 'Havells Euro II 40A Double Pole MCB C Curve',
    modelNumber: 'DHMGCDPF040',
    sku: 'HAV-MCB-DP-40A-C',
    description: 'Double pole MCB with 10kA breaking capacity for main isolation.',
    specifications: JSON.stringify({
      poles: 2,
      rating: '40A',
      curve: 'C',
      breakingCapacity: '10kA',
      voltage: '240V AC',
      width: '35mm (2 modules)',
      standard: 'IS/IEC 60898',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/havells-mcb-dp-40a.jpg'],
  },
  {
    brand: 'havells',
    productType: 'dp-mcb',
    name: 'Havells Euro II 63A Double Pole MCB C Curve',
    modelNumber: 'DHMGCDPF063',
    sku: 'HAV-MCB-DP-63A-C',
    description: 'Double pole MCB with 10kA breaking capacity for main incomer.',
    specifications: JSON.stringify({
      poles: 2,
      rating: '63A',
      curve: 'C',
      breakingCapacity: '10kA',
      voltage: '240V AC',
      width: '35mm (2 modules)',
      standard: 'IS/IEC 60898',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/havells-mcb-dp-63a.jpg'],
  },

  // Polycab MCBs
  {
    brand: 'polycab',
    productType: 'sp-mcb',
    name: 'Polycab Safeguard 16A Single Pole MCB C Curve 10kA',
    modelNumber: 'GMM101P016',
    sku: 'POL-MCB-SP-16A-C',
    description: 'Single pole MCB with 10kA breaking capacity for residential use.',
    specifications: JSON.stringify({
      poles: 1,
      rating: '16A',
      curve: 'C',
      breakingCapacity: '10kA',
      voltage: '240V AC',
      width: '18mm (1 module)',
      standard: 'IS/IEC 60898',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/polycab-mcb-sp-16a.jpg'],
  },
  {
    brand: 'polycab',
    productType: 'sp-mcb',
    name: 'Polycab Safeguard 32A Single Pole MCB C Curve 10kA',
    modelNumber: 'GMM101P032',
    sku: 'POL-MCB-SP-32A-C',
    description: 'Single pole MCB with 10kA breaking capacity for heavy loads.',
    specifications: JSON.stringify({
      poles: 1,
      rating: '32A',
      curve: 'C',
      breakingCapacity: '10kA',
      voltage: '240V AC',
      width: '18mm (1 module)',
      standard: 'IS/IEC 60898',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/polycab-mcb-sp-32a.jpg'],
  },
  {
    brand: 'polycab',
    productType: 'dc-mcb',
    name: 'Polycab DC MCB 40A Four Pole 6kA',
    modelNumber: 'GMM404P007',
    sku: 'POL-DCM-FP-40A',
    description: 'DC MCB for solar applications with 6kA breaking capacity.',
    specifications: JSON.stringify({
      poles: 4,
      rating: '40A',
      type: 'DC',
      breakingCapacity: '6kA',
      voltage: '1000V DC',
      width: '72mm (4 modules)',
      application: 'Solar PV Systems',
    }),
    certifications: ['IEC'],
    warrantyYears: 2,
    images: ['/products/polycab-dcmcb-40a.jpg'],
  },
  {
    brand: 'polycab',
    productType: 'dc-mcb',
    name: 'Polycab DC MCB 63A Four Pole 6kA',
    modelNumber: 'GMM404P008',
    sku: 'POL-DCM-FP-63A',
    description: 'DC MCB for solar applications with 6kA breaking capacity.',
    specifications: JSON.stringify({
      poles: 4,
      rating: '63A',
      type: 'DC',
      breakingCapacity: '6kA',
      voltage: '1000V DC',
      width: '72mm (4 modules)',
      application: 'Solar PV Systems',
    }),
    certifications: ['IEC'],
    warrantyYears: 2,
    images: ['/products/polycab-dcmcb-63a.jpg'],
  },

  // Legrand MCBs
  {
    brand: 'legrand',
    productType: 'sp-mcb',
    name: 'Legrand RX3 16A Single Pole MCB C Curve',
    modelNumber: '419662',
    sku: 'LEG-RX3-SP-16A',
    description: 'Premium single pole MCB with excellent performance and reliability.',
    specifications: JSON.stringify({
      poles: 1,
      rating: '16A',
      curve: 'C',
      breakingCapacity: '6kA',
      voltage: '240V AC',
      width: '17.5mm (1 module)',
      standard: 'IS/IEC 60898',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/legrand-rx3-16a.jpg'],
  },
  {
    brand: 'legrand',
    productType: 'sp-mcb',
    name: 'Legrand DX3 16A Single Pole MCB C Curve 10kA',
    modelNumber: '411003',
    sku: 'LEG-DX3-SP-16A',
    description: 'Premium single pole MCB with 10kA breaking capacity.',
    specifications: JSON.stringify({
      poles: 1,
      rating: '16A',
      curve: 'C',
      breakingCapacity: '10kA',
      voltage: '240V AC',
      width: '17.5mm (1 module)',
      standard: 'IS/IEC 60898',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/legrand-dx3-16a.jpg'],
  },

  // ========== RCCB ==========
  {
    brand: 'havells',
    productType: 'dp-rccb',
    name: 'Havells 40A 30mA Double Pole RCCB',
    modelNumber: 'DHRMAHDF040030',
    sku: 'HAV-RCCB-DP-40A',
    description: 'Double pole RCCB for earth leakage protection. 30mA sensitivity.',
    specifications: JSON.stringify({
      poles: 2,
      rating: '40A',
      sensitivity: '30mA',
      breakingCapacity: '6kA',
      voltage: '240V AC',
      width: '35mm (2 modules)',
      standard: 'IS/IEC 61008',
      tripTime: '<40ms',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/havells-rccb-40a.jpg'],
  },
  {
    brand: 'havells',
    productType: 'dp-rccb',
    name: 'Havells 63A 30mA Double Pole RCCB',
    modelNumber: 'DHRMAHDF063030',
    sku: 'HAV-RCCB-DP-63A',
    description: 'Double pole RCCB for earth leakage protection. Main incomer protection.',
    specifications: JSON.stringify({
      poles: 2,
      rating: '63A',
      sensitivity: '30mA',
      breakingCapacity: '6kA',
      voltage: '240V AC',
      width: '35mm (2 modules)',
      standard: 'IS/IEC 61008',
      tripTime: '<40ms',
    }),
    certifications: ['ISI', 'IEC'],
    warrantyYears: 2,
    images: ['/products/havells-rccb-63a.jpg'],
  },

  // ========== DISTRIBUTION BOARDS ==========
  {
    brand: 'havells',
    productType: 'spn-db',
    name: 'Havells 4 Way SPN Distribution Board - Double Door',
    modelNumber: 'DHDNSHOFW04',
    sku: 'HAV-DB-SPN-4W',
    description: 'Single phase distribution board with 4 outgoing ways. Double door design.',
    specifications: JSON.stringify({
      type: 'SPN',
      ways: 4,
      incomer: 'DP MCB/Isolator',
      mounting: 'Surface/Flush',
      material: 'Sheet Steel',
      door: 'Double Door',
      ipRating: 'IP30',
    }),
    certifications: ['ISI'],
    warrantyYears: 1,
    images: ['/products/havells-db-4w.jpg'],
  },
  {
    brand: 'havells',
    productType: 'spn-db',
    name: 'Havells 8 Way SPN Distribution Board - Double Door',
    modelNumber: 'DHDNSHOFW08',
    sku: 'HAV-DB-SPN-8W',
    description: 'Single phase distribution board with 8 outgoing ways. Double door design.',
    specifications: JSON.stringify({
      type: 'SPN',
      ways: 8,
      incomer: 'DP MCB/Isolator',
      mounting: 'Surface/Flush',
      material: 'Sheet Steel',
      door: 'Double Door',
      ipRating: 'IP30',
    }),
    certifications: ['ISI'],
    warrantyYears: 1,
    images: ['/products/havells-db-8w.jpg'],
  },
  {
    brand: 'havells',
    productType: 'spn-db',
    name: 'Havells 12 Way SPN Distribution Board - Double Door',
    modelNumber: 'DHDNSHOFW12',
    sku: 'HAV-DB-SPN-12W',
    description: 'Single phase distribution board with 12 outgoing ways. Double door design.',
    specifications: JSON.stringify({
      type: 'SPN',
      ways: 12,
      incomer: 'DP MCB/Isolator',
      mounting: 'Surface/Flush',
      material: 'Sheet Steel',
      door: 'Double Door',
      ipRating: 'IP30',
    }),
    certifications: ['ISI'],
    warrantyYears: 1,
    images: ['/products/havells-db-12w.jpg'],
  },

  // ========== CEILING FANS ==========
  // Havells Fans
  {
    brand: 'havells',
    productType: 'standard-fan',
    name: 'Havells SS-390 1200mm Ceiling Fan',
    modelNumber: 'FHCSSSTIVR48',
    sku: 'HAV-FAN-SS390-48',
    description: 'Classic ceiling fan with elegant design and powerful air delivery.',
    specifications: JSON.stringify({
      sweep: '1200mm (48 inch)',
      speed: '350 RPM',
      power: '75W',
      airDelivery: '230 CMM',
      blades: 3,
      material: 'Aluminium',
      color: ['Ivory', 'Brown', 'White'],
      starRating: 'Non-Star',
      motorType: 'Induction',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/havells-ss390.jpg'],
  },
  {
    brand: 'havells',
    productType: 'bldc-fan',
    name: 'Havells Efficiencia Neo BLDC 1200mm Ceiling Fan',
    modelNumber: 'FHCBFSTBLU48',
    sku: 'HAV-BLDC-EFFNEO-48',
    description: 'Energy efficient BLDC ceiling fan with remote control. Saves up to 50% energy.',
    specifications: JSON.stringify({
      sweep: '1200mm (48 inch)',
      speed: '330 RPM',
      power: '26W',
      airDelivery: '210 CMM',
      blades: 3,
      material: 'ABS',
      color: ['Bianco', 'Mist Grey'],
      starRating: '5 Star',
      motorType: 'BLDC',
      remote: 'Yes',
      timer: 'Yes',
      reverseMode: 'Yes',
    }),
    certifications: ['ISI', 'BEE 5 Star'],
    warrantyYears: 2,
    images: ['/products/havells-efficiencia-neo.jpg'],
  },
  {
    brand: 'havells',
    productType: 'bldc-fan',
    name: 'Havells Stealth Air BLDC 1200mm Ceiling Fan',
    modelNumber: 'FHCBFSTAIR48',
    sku: 'HAV-BLDC-STEALTH-48',
    description: 'Premium BLDC ceiling fan with aerodynamic design and IoT enabled.',
    specifications: JSON.stringify({
      sweep: '1200mm (48 inch)',
      speed: '350 RPM',
      power: '40W',
      airDelivery: '230 CMM',
      blades: 3,
      material: 'ABS',
      color: ['Charcoal Grey', 'Pristine White'],
      starRating: '5 Star',
      motorType: 'BLDC',
      remote: 'Yes',
      timer: 'Yes',
      iotEnabled: 'Yes',
    }),
    certifications: ['ISI', 'BEE 5 Star'],
    warrantyYears: 2,
    images: ['/products/havells-stealth-air.jpg'],
  },

  // Crompton Fans
  {
    brand: 'crompton',
    productType: 'standard-fan',
    name: 'Crompton Hill Briz 1200mm Ceiling Fan',
    modelNumber: 'CFSNHBZ48WH',
    sku: 'CRO-FAN-HILLBRIZ-48',
    description: 'High speed ceiling fan with powerful motor and elegant design.',
    specifications: JSON.stringify({
      sweep: '1200mm (48 inch)',
      speed: '390 RPM',
      power: '72W',
      airDelivery: '240 CMM',
      blades: 3,
      material: 'Aluminium',
      color: ['White', 'Ivory', 'Brown'],
      starRating: 'Non-Star',
      motorType: 'Induction',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/crompton-hillbriz.jpg'],
  },
  {
    brand: 'crompton',
    productType: 'bldc-fan',
    name: 'Crompton Energion HS BLDC 1200mm Ceiling Fan',
    modelNumber: 'CFBLENHS48',
    sku: 'CRO-BLDC-ENERGION-48',
    description: 'Active BLDC technology ceiling fan with superior air delivery.',
    specifications: JSON.stringify({
      sweep: '1200mm (48 inch)',
      speed: '370 RPM',
      power: '35W',
      airDelivery: '220 CMM',
      blades: 3,
      material: 'ABS',
      color: ['White', 'Brown'],
      starRating: '5 Star',
      motorType: 'BLDC',
      remote: 'Yes',
      timer: 'Yes',
    }),
    certifications: ['ISI', 'BEE 5 Star'],
    warrantyYears: 2,
    images: ['/products/crompton-energion.jpg'],
  },

  // Orient Fans
  {
    brand: 'orient',
    productType: 'standard-fan',
    name: 'Orient Electric Apex-FX 1200mm Ceiling Fan',
    modelNumber: 'APEX-FX-48',
    sku: 'ORI-FAN-APEXFX-48',
    description: 'Budget friendly ceiling fan with reliable performance.',
    specifications: JSON.stringify({
      sweep: '1200mm (48 inch)',
      speed: '350 RPM',
      power: '75W',
      airDelivery: '210 CMM',
      blades: 3,
      material: 'Aluminium',
      color: ['White', 'Ivory', 'Brown'],
      starRating: 'Non-Star',
      motorType: 'Induction',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/orient-apexfx.jpg'],
  },
  {
    brand: 'orient',
    productType: 'bldc-fan',
    name: 'Orient Electric Aeroquiet BLDC 1200mm Ceiling Fan',
    modelNumber: 'AEROQUIET-48',
    sku: 'ORI-BLDC-AEROQUIET-48',
    description: 'Super silent BLDC ceiling fan with inverter compatible operation.',
    specifications: JSON.stringify({
      sweep: '1200mm (48 inch)',
      speed: '380 RPM',
      power: '32W',
      airDelivery: '225 CMM',
      blades: 3,
      material: 'ABS',
      color: ['Pearl White', 'Metallic Brown'],
      starRating: '5 Star',
      motorType: 'BLDC',
      remote: 'Yes',
      timer: 'Yes',
      noiseLevel: '<48 dB',
    }),
    certifications: ['ISI', 'BEE 5 Star'],
    warrantyYears: 2,
    images: ['/products/orient-aeroquiet.jpg'],
  },

  // Atomberg Fans
  {
    brand: 'atomberg',
    productType: 'bldc-fan',
    name: 'Atomberg Efficio 1200mm BLDC Ceiling Fan',
    modelNumber: 'EFFICIO-48-WHT',
    sku: 'ATM-BLDC-EFFICIO-48',
    description: 'India\'s most energy efficient ceiling fan with Gorilla BLDC technology.',
    specifications: JSON.stringify({
      sweep: '1200mm (48 inch)',
      speed: '390 RPM',
      power: '28W',
      airDelivery: '230 CMM',
      blades: 3,
      material: 'ABS',
      color: ['Matt White', 'Matt Black', 'Gloss Ivory'],
      starRating: '5 Star',
      motorType: 'BLDC',
      remote: 'Yes',
      timer: 'Yes with 6hr boost',
      LED: 'Yes (LED indicator)',
    }),
    certifications: ['ISI', 'BEE 5 Star'],
    warrantyYears: 2,
    images: ['/products/atomberg-efficio.jpg'],
  },
  {
    brand: 'atomberg',
    productType: 'bldc-fan',
    name: 'Atomberg Renesa 1200mm Smart BLDC Ceiling Fan',
    modelNumber: 'RENESA-48-WHT',
    sku: 'ATM-BLDC-RENESA-48',
    description: 'Smart ceiling fan with Alexa and Google Home compatibility.',
    specifications: JSON.stringify({
      sweep: '1200mm (48 inch)',
      speed: '400 RPM',
      power: '32W',
      airDelivery: '240 CMM',
      blades: 3,
      material: 'ABS',
      color: ['Marble White', 'Midnight Black'],
      starRating: '5 Star',
      motorType: 'BLDC',
      remote: 'Yes',
      timer: 'Yes',
      smartEnabled: 'Yes - WiFi',
      voiceControl: 'Alexa, Google Home',
    }),
    certifications: ['ISI', 'BEE 5 Star'],
    warrantyYears: 2,
    images: ['/products/atomberg-renesa.jpg'],
  },

  // ========== LED BULBS ==========
  // Philips LEDs
  {
    brand: 'philips',
    productType: 'led-bulb-b22',
    name: 'Philips Ace Saver 9W LED Bulb B22 6500K',
    modelNumber: 'PLED-ACE-9W-65K',
    sku: 'PHI-LED-9W-B22-CDL',
    description: 'Energy efficient LED bulb with cool daylight color. Ideal for general lighting.',
    specifications: JSON.stringify({
      wattage: '9W',
      lumens: '806 lm',
      efficacy: '90 lm/W',
      base: 'B22 (Bayonet)',
      colorTemp: '6500K (Cool Daylight)',
      cri: '>80',
      beamAngle: '200°',
      lifespan: '15000 hours',
      voltage: '220-240V',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/philips-ace-9w.jpg'],
  },
  {
    brand: 'philips',
    productType: 'led-bulb-b22',
    name: 'Philips Stellar Bright 14W LED Bulb B22 6500K',
    modelNumber: 'PLED-STL-14W-65K',
    sku: 'PHI-LED-14W-B22-CDL',
    description: 'High lumen LED bulb for bright illumination. 100 lm/W efficiency.',
    specifications: JSON.stringify({
      wattage: '14W',
      lumens: '1400 lm',
      efficacy: '100 lm/W',
      base: 'B22 (Bayonet)',
      colorTemp: '6500K (Cool Daylight)',
      cri: '>80',
      beamAngle: '200°',
      lifespan: '15000 hours',
      voltage: '220-240V',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/philips-stellar-14w.jpg'],
  },
  {
    brand: 'philips',
    productType: 'led-bulb-b22',
    name: 'Philips 20W High Wattage LED Bulb B22 6500K',
    modelNumber: 'PLED-HW-20W-65K',
    sku: 'PHI-LED-20W-B22-CDL',
    description: 'High wattage LED bulb for large rooms. Equivalent to 32W CFL.',
    specifications: JSON.stringify({
      wattage: '20W',
      lumens: '2000 lm',
      efficacy: '100 lm/W',
      base: 'B22 (Bayonet)',
      colorTemp: '6500K (Cool Daylight)',
      cri: '>80',
      beamAngle: '200°',
      lifespan: '25000 hours',
      voltage: '220-240V',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/philips-20w.jpg'],
  },

  // Syska LEDs
  {
    brand: 'syska',
    productType: 'led-bulb-b22',
    name: 'Syska SSK-SRL 9W LED Bulb B22 6500K',
    modelNumber: 'SSK-SRL-9W-65K',
    sku: 'SYS-LED-9W-B22-CDL',
    description: 'Energy saving LED bulb with instant start and no warm-up time.',
    specifications: JSON.stringify({
      wattage: '9W',
      lumens: '720 lm',
      efficacy: '80 lm/W',
      base: 'B22 (Bayonet)',
      colorTemp: '6500K (Cool Daylight)',
      cri: '>70',
      beamAngle: '180°',
      lifespan: '25000 hours',
      voltage: '220-240V',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/syska-9w.jpg'],
  },
  {
    brand: 'syska',
    productType: 'led-bulb-b22',
    name: 'Syska SSK-SRL 12W LED Bulb B22 6500K',
    modelNumber: 'SSK-SRL-12W-65K',
    sku: 'SYS-LED-12W-B22-CDL',
    description: 'High brightness LED bulb for living rooms and halls.',
    specifications: JSON.stringify({
      wattage: '12W',
      lumens: '1020 lm',
      efficacy: '85 lm/W',
      base: 'B22 (Bayonet)',
      colorTemp: '6500K (Cool Daylight)',
      cri: '>70',
      beamAngle: '180°',
      lifespan: '25000 hours',
      voltage: '220-240V',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/syska-12w.jpg'],
  },
  {
    brand: 'syska',
    productType: 'led-bulb-b22',
    name: 'Syska SSK-SRL 18W LED Bulb B22 6500K',
    modelNumber: 'SSK-SRL-18W-65K',
    sku: 'SYS-LED-18W-B22-CDL',
    description: 'High wattage LED bulb for large spaces.',
    specifications: JSON.stringify({
      wattage: '18W',
      lumens: '1620 lm',
      efficacy: '90 lm/W',
      base: 'B22 (Bayonet)',
      colorTemp: '6500K (Cool Daylight)',
      cri: '>70',
      beamAngle: '180°',
      lifespan: '25000 hours',
      voltage: '220-240V',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/syska-18w.jpg'],
  },

  // Wipro LEDs
  {
    brand: 'wipro',
    productType: 'led-bulb-b22',
    name: 'Wipro Garnet 9W LED Bulb B22 6500K',
    modelNumber: 'N90001',
    sku: 'WIP-LED-9W-B22-CDL',
    description: 'Energy efficient LED bulb with 80% energy saving vs incandescent.',
    specifications: JSON.stringify({
      wattage: '9W',
      lumens: '810 lm',
      efficacy: '90 lm/W',
      base: 'B22 (Bayonet)',
      colorTemp: '6500K (Cool Daylight)',
      cri: '>80',
      beamAngle: '200°',
      lifespan: '25000 hours',
      voltage: '220-240V',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/wipro-garnet-9w.jpg'],
  },

  // LED Panels
  {
    brand: 'philips',
    productType: 'round-panel',
    name: 'Philips Star Surface 12W Round LED Panel Light',
    modelNumber: 'PLED-PNL-12W-R',
    sku: 'PHI-PNL-12W-SURF-R',
    description: 'Surface mounted round LED panel for modern interiors.',
    specifications: JSON.stringify({
      wattage: '12W',
      lumens: '1200 lm',
      efficacy: '100 lm/W',
      colorTemp: '6500K (Cool Daylight)',
      cutout: '150mm',
      outerDia: '170mm',
      thickness: '35mm',
      mounting: 'Surface',
      driver: 'Built-in',
      lifespan: '25000 hours',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/philips-panel-12w.jpg'],
  },
  {
    brand: 'philips',
    productType: 'round-panel',
    name: 'Philips Star Surface 18W Round LED Panel Light',
    modelNumber: 'PLED-PNL-18W-R',
    sku: 'PHI-PNL-18W-SURF-R',
    description: 'Surface mounted round LED panel for large rooms.',
    specifications: JSON.stringify({
      wattage: '18W',
      lumens: '1800 lm',
      efficacy: '100 lm/W',
      colorTemp: '6500K (Cool Daylight)',
      cutout: '200mm',
      outerDia: '220mm',
      thickness: '35mm',
      mounting: 'Surface',
      driver: 'Built-in',
      lifespan: '25000 hours',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 2,
    images: ['/products/philips-panel-18w.jpg'],
  },
  {
    brand: 'philips',
    productType: '2x2-panel',
    name: 'Philips RC360B 36W 2x2 LED Panel 6500K',
    modelNumber: 'RC360B-LED36S',
    sku: 'PHI-PNL-36W-2X2',
    description: 'Commercial grade 2x2 LED panel for offices and commercial spaces.',
    specifications: JSON.stringify({
      wattage: '36W',
      lumens: '3600 lm',
      efficacy: '100 lm/W',
      colorTemp: '6500K (Cool Daylight)',
      size: '600x600mm (2x2 ft)',
      thickness: '9mm',
      mounting: 'Recessed/Grid',
      driver: 'External',
      lifespan: '50000 hours',
      cri: '>80',
    }),
    certifications: ['ISI', 'BEE'],
    warrantyYears: 3,
    images: ['/products/philips-panel-36w-2x2.jpg'],
  },

  // ========== SWITCHES & SOCKETS ==========
  // Havells Switches
  {
    brand: 'havells',
    productType: 'one-way',
    name: 'Havells Pearlz 6A One Way Switch',
    modelNumber: 'AHEPEXW061',
    sku: 'HAV-SW-PEARLZ-1W-6A',
    description: 'Premium modular switch with silver alloy contacts for long life.',
    specifications: JSON.stringify({
      type: 'One Way',
      rating: '6A 240V AC',
      size: '1 Module',
      contacts: 'Silver Alloy',
      operations: '100,000 cycles',
      color: 'White',
      series: 'Pearlz',
    }),
    certifications: ['ISI'],
    warrantyYears: 10,
    images: ['/products/havells-pearlz-1w.jpg'],
  },
  {
    brand: 'havells',
    productType: 'two-way',
    name: 'Havells Pearlz 6A Two Way Switch',
    modelNumber: 'AHEPEXW062',
    sku: 'HAV-SW-PEARLZ-2W-6A',
    description: 'Two way switch for staircase and corridor lighting control.',
    specifications: JSON.stringify({
      type: 'Two Way',
      rating: '6A 240V AC',
      size: '1 Module',
      contacts: 'Silver Alloy',
      operations: '100,000 cycles',
      color: 'White',
      series: 'Pearlz',
    }),
    certifications: ['ISI'],
    warrantyYears: 10,
    images: ['/products/havells-pearlz-2w.jpg'],
  },
  {
    brand: 'havells',
    productType: '6a-socket',
    name: 'Havells Pearlz 6A 3 Pin Socket',
    modelNumber: 'AHEPSXW061',
    sku: 'HAV-SOC-PEARLZ-6A',
    description: '6A socket for mobile chargers and low power devices.',
    specifications: JSON.stringify({
      type: '3 Pin Socket',
      rating: '6A 240V AC',
      size: '2 Modules',
      shuttered: 'Yes',
      color: 'White',
      series: 'Pearlz',
    }),
    certifications: ['ISI'],
    warrantyYears: 10,
    images: ['/products/havells-pearlz-socket-6a.jpg'],
  },
  {
    brand: 'havells',
    productType: '16a-socket',
    name: 'Havells Pearlz 16A 3 Pin Socket',
    modelNumber: 'AHEPSXW161',
    sku: 'HAV-SOC-PEARLZ-16A',
    description: '16A socket for AC, geyser, and heavy appliances.',
    specifications: JSON.stringify({
      type: '3 Pin Socket',
      rating: '16A 240V AC',
      size: '3 Modules',
      shuttered: 'Yes',
      color: 'White',
      series: 'Pearlz',
    }),
    certifications: ['ISI'],
    warrantyYears: 10,
    images: ['/products/havells-pearlz-socket-16a.jpg'],
  },
  {
    brand: 'havells',
    productType: 'fan-regulator',
    name: 'Havells Pearlz 5 Step Fan Regulator',
    modelNumber: 'AHEPRXW051',
    sku: 'HAV-REG-PEARLZ-5STEP',
    description: '5 step fan regulator with smooth speed control.',
    specifications: JSON.stringify({
      type: 'Step Type',
      steps: 5,
      rating: '100W',
      size: '2 Modules',
      color: 'White',
      series: 'Pearlz',
    }),
    certifications: ['ISI'],
    warrantyYears: 5,
    images: ['/products/havells-pearlz-regulator.jpg'],
  },

  // Anchor Switches
  {
    brand: 'anchor',
    productType: 'one-way',
    name: 'Anchor Roma Classic 6A One Way Switch',
    modelNumber: 'AR-RC-1W-6A',
    sku: 'ANC-SW-ROMA-1W-6A',
    description: 'Classic modular switch with high quality construction.',
    specifications: JSON.stringify({
      type: 'One Way',
      rating: '6A 240V AC',
      size: '1 Module',
      contacts: 'Silver',
      operations: '50,000 cycles',
      color: 'White',
      series: 'Roma Classic',
    }),
    certifications: ['ISI'],
    warrantyYears: 5,
    images: ['/products/anchor-roma-1w.jpg'],
  },
  {
    brand: 'anchor',
    productType: 'two-way',
    name: 'Anchor Roma Classic 6A Two Way Switch',
    modelNumber: 'AR-RC-2W-6A',
    sku: 'ANC-SW-ROMA-2W-6A',
    description: 'Two way switch for multi-point lighting control.',
    specifications: JSON.stringify({
      type: 'Two Way',
      rating: '6A 240V AC',
      size: '1 Module',
      contacts: 'Silver',
      operations: '50,000 cycles',
      color: 'White',
      series: 'Roma Classic',
    }),
    certifications: ['ISI'],
    warrantyYears: 5,
    images: ['/products/anchor-roma-2w.jpg'],
  },

  // Legrand Switches
  {
    brand: 'legrand',
    productType: 'one-way',
    name: 'Legrand Myrius 6A One Way Switch',
    modelNumber: 'LG-MY-1W-6A',
    sku: 'LEG-SW-MYRIUS-1W-6A',
    description: 'Premium modular switch with click-fit mechanism.',
    specifications: JSON.stringify({
      type: 'One Way',
      rating: '6A 240V AC',
      size: '1 Module',
      contacts: 'Silver Nickel',
      operations: '100,000 cycles',
      color: 'White',
      series: 'Myrius',
    }),
    certifications: ['ISI'],
    warrantyYears: 15,
    images: ['/products/legrand-myrius-1w.jpg'],
  },
  {
    brand: 'legrand',
    productType: '16a-socket',
    name: 'Legrand Myrius 16A 3 Pin Socket',
    modelNumber: 'LG-MY-SOC-16A',
    sku: 'LEG-SOC-MYRIUS-16A',
    description: 'Heavy duty socket with child protection shutters.',
    specifications: JSON.stringify({
      type: '3 Pin Socket',
      rating: '16A 240V AC',
      size: '3 Modules',
      shuttered: 'Yes',
      color: 'White',
      series: 'Myrius',
    }),
    certifications: ['ISI'],
    warrantyYears: 15,
    images: ['/products/legrand-myrius-socket-16a.jpg'],
  },

  // ========== WATER HEATERS ==========
  {
    brand: 'havells',
    productType: 'vertical-geyser',
    name: 'Havells Instanio Prime 15L Storage Water Heater',
    modelNumber: 'GHWAIPMWH015',
    sku: 'HAV-GEY-INSTANIO-15L',
    description: '5 star rated storage water heater with superior insulation.',
    specifications: JSON.stringify({
      capacity: '15 Liters',
      power: '2000W',
      voltage: '230V',
      starRating: '5 Star',
      tankMaterial: 'Stainless Steel',
      element: 'Incoloy 800',
      thermostat: 'Capillary',
      pressureRating: '8 Bar',
      mounting: 'Vertical',
    }),
    certifications: ['ISI', 'BEE 5 Star'],
    warrantyYears: 5,
    images: ['/products/havells-instanio-15l.jpg'],
  },
  {
    brand: 'havells',
    productType: 'vertical-geyser',
    name: 'Havells Instanio Prime 25L Storage Water Heater',
    modelNumber: 'GHWAIPMWH025',
    sku: 'HAV-GEY-INSTANIO-25L',
    description: '5 star rated storage water heater for larger families.',
    specifications: JSON.stringify({
      capacity: '25 Liters',
      power: '2000W',
      voltage: '230V',
      starRating: '5 Star',
      tankMaterial: 'Stainless Steel',
      element: 'Incoloy 800',
      thermostat: 'Capillary',
      pressureRating: '8 Bar',
      mounting: 'Vertical',
    }),
    certifications: ['ISI', 'BEE 5 Star'],
    warrantyYears: 5,
    images: ['/products/havells-instanio-25l.jpg'],
  },
  {
    brand: 'bajaj',
    productType: 'vertical-geyser',
    name: 'Bajaj New Shakti Neo 15L Storage Water Heater',
    modelNumber: 'BJ-NSN-15L',
    sku: 'BAJ-GEY-SHAKTINE-15L',
    description: 'Affordable storage water heater with glasslined tank.',
    specifications: JSON.stringify({
      capacity: '15 Liters',
      power: '2000W',
      voltage: '230V',
      starRating: '4 Star',
      tankMaterial: 'Glasslined',
      element: 'Copper',
      thermostat: 'Capillary',
      pressureRating: '6.5 Bar',
      mounting: 'Vertical',
    }),
    certifications: ['ISI', 'BEE 4 Star'],
    warrantyYears: 2,
    images: ['/products/bajaj-shakti-15l.jpg'],
  },
  {
    brand: 'vguard',
    productType: 'instant-geyser',
    name: 'V-Guard Sprinhot Plus 3L Instant Water Heater',
    modelNumber: 'VG-SHP-3L',
    sku: 'VGU-GEY-SPRING-3L',
    description: 'Compact instant water heater for quick hot water.',
    specifications: JSON.stringify({
      capacity: '3 Liters',
      power: '3000W',
      voltage: '230V',
      tankMaterial: 'ABS Plastic',
      element: 'Copper',
      thermostat: 'Automatic',
      mounting: 'Wall',
      recovery: '5 min',
    }),
    certifications: ['ISI'],
    warrantyYears: 2,
    images: ['/products/vguard-sprinhot-3l.jpg'],
  },

  // ========== EXHAUST FANS ==========
  {
    brand: 'havells',
    productType: 'domestic-exhaust',
    name: 'Havells Ventilair DX 150mm Exhaust Fan',
    modelNumber: 'FHVVDSTIVR06',
    sku: 'HAV-EXH-VENTILAIR-6',
    description: '150mm domestic exhaust fan for bathrooms and kitchens.',
    specifications: JSON.stringify({
      sweep: '150mm (6 inch)',
      power: '20W',
      airDelivery: '200 CMH',
      speed: '2200 RPM',
      noise: '<45 dB',
      mounting: 'Window/Wall',
      blades: 5,
    }),
    certifications: ['ISI'],
    warrantyYears: 2,
    images: ['/products/havells-ventilair-6.jpg'],
  },
  {
    brand: 'havells',
    productType: 'domestic-exhaust',
    name: 'Havells Ventilair DX 200mm Exhaust Fan',
    modelNumber: 'FHVVDSTIVR08',
    sku: 'HAV-EXH-VENTILAIR-8',
    description: '200mm domestic exhaust fan for medium size rooms.',
    specifications: JSON.stringify({
      sweep: '200mm (8 inch)',
      power: '28W',
      airDelivery: '320 CMH',
      speed: '1850 RPM',
      noise: '<48 dB',
      mounting: 'Window/Wall',
      blades: 5,
    }),
    certifications: ['ISI'],
    warrantyYears: 2,
    images: ['/products/havells-ventilair-8.jpg'],
  },
  {
    brand: 'crompton',
    productType: 'domestic-exhaust',
    name: 'Crompton Brisk Air 150mm Exhaust Fan',
    modelNumber: 'CF-BA-6',
    sku: 'CRO-EXH-BRISK-6',
    description: 'High performance exhaust fan with anti-dust oil technology.',
    specifications: JSON.stringify({
      sweep: '150mm (6 inch)',
      power: '18W',
      airDelivery: '210 CMH',
      speed: '2100 RPM',
      noise: '<44 dB',
      mounting: 'Window/Wall',
      blades: 5,
    }),
    certifications: ['ISI'],
    warrantyYears: 2,
    images: ['/products/crompton-brisk-6.jpg'],
  },
];
