// Realistic electrical products for Indian real estate market
// Based on actual products from Polycab, Havells, Schneider, L&T, Anchor, etc.

export const realisticProducts = [
  // WIRES & CABLES
  {
    name: 'Polycab FR PVC Insulated Cable 1.5 sq mm',
    category: 'ELECTRICAL_WIRING',
    brand: 'Polycab',
    description: 'Flame retardant PVC insulated unsheathed industrial cables for fixed indoor wiring. IS 694:2010 compliant. Ideal for residential and commercial installations.',
    specifications: {
      wireSize: '1.5 sq mm',
      conductor: '100% Electrolytic Grade Copper',
      insulation: 'FR PVC',
      voltage: '1100V',
      standard: 'IS 694:2010',
      temperature: '70°C',
      colors: ['Red', 'Black', 'Blue', 'Yellow', 'Green'],
    },
    priceRange: { min: 28, max: 35, unit: 'per meter' },
    imageUrl: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?w=500',
    popular: true,
  },
  {
    name: 'Havells HRFR Cable 2.5 sq mm',
    category: 'ELECTRICAL_WIRING',
    brand: 'Havells',
    description: 'Heat Resistant Flame Retardant cables with superior insulation. Perfect for high-load circuits like AC, geyser, and kitchen appliances.',
    specifications: {
      wireSize: '2.5 sq mm',
      conductor: 'Annealed Copper',
      insulation: 'HRFR PVC',
      voltage: '1100V',
      standard: 'IS 694:2010',
      temperature: '90°C',
      colors: ['Red', 'Black', 'Blue'],
    },
    priceRange: { min: 45, max: 55, unit: 'per meter' },
    imageUrl: 'https://images.unsplash.com/photo-1473186578172-c141e6798cf4?w=500',
    popular: true,
  },
  {
    name: 'Polycab Submersible Flat Cable 4 Core x 4 sq mm',
    category: 'ELECTRICAL_WIRING',
    brand: 'Polycab',
    description: 'Specially designed for submersible pump installations. Water-resistant jacket with excellent mechanical strength.',
    specifications: {
      wireSize: '4 sq mm x 4 Core',
      conductor: 'Tinned Copper',
      insulation: 'HRPVC + PVC Sheath',
      voltage: '1100V',
      application: 'Submersible Pumps',
      temperature: '90°C',
    },
    priceRange: { min: 180, max: 220, unit: 'per meter' },
    imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500',
  },
  {
    name: 'KEI 3 Core Flexible Cable 1.5 sq mm',
    category: 'ELECTRICAL_WIRING',
    brand: 'KEI',
    description: 'Flexible multi-core cable for appliances and power cords. Highly flexible stranded copper conductors.',
    specifications: {
      wireSize: '1.5 sq mm x 3 Core',
      conductor: 'Flexible Stranded Copper',
      insulation: 'PVC',
      voltage: '1100V',
      cores: 3,
      flexibility: 'High',
    },
    priceRange: { min: 38, max: 45, unit: 'per meter' },
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=500',
  },

  // MODULAR SWITCHES & SOCKETS
  {
    name: 'Schneider Livia 6A 1-Way Switch - White',
    category: 'SWITCHES_SOCKETS',
    brand: 'Schneider Electric',
    description: 'Premium modular switch with elegant white finish. Smooth ON/OFF operation with 100,000+ switching cycles. 10-year warranty.',
    specifications: {
      rating: '6A/10A, 240V',
      type: '1-Way',
      material: 'Polycarbonate',
      finish: 'Glossy White',
      plateSize: '2 Module',
      warranty: '10 Years',
      features: ['Ergonomic Rocker', 'LED Indicator Option', 'Child Safe'],
    },
    priceRange: { min: 85, max: 110, unit: 'per piece' },
    imageUrl: 'https://images.unsplash.com/photo-1562141968-fbf3b5c5a459?w=500',
    popular: true,
  },
  {
    name: 'Anchor Roma 16A 3-Pin Socket',
    category: 'SWITCHES_SOCKETS',
    brand: 'Anchor',
    description: 'Heavy-duty 3-pin socket for high-power appliances. Universal shutter system for enhanced safety. Suitable for AC, refrigerator, washing machine.',
    specifications: {
      rating: '16A, 240V',
      type: '3-Pin Socket with Earth',
      material: 'Fire-Retardant Plastic',
      shutter: 'Universal Shutter System',
      applications: ['Air Conditioner', 'Washing Machine', 'Refrigerator'],
    },
    priceRange: { min: 120, max: 150, unit: 'per piece' },
    imageUrl: 'https://images.unsplash.com/photo-1585338107529-13afc5f02586?w=500',
    popular: true,
  },
  {
    name: 'Legrand Myrius 6A Bell Push Switch',
    category: 'SWITCHES_SOCKETS',
    brand: 'Legrand',
    description: 'Elegant bell push switch for doorbell connections. Momentary contact with smooth press action.',
    specifications: {
      rating: '6A, 240V',
      type: 'Bell Push (Momentary)',
      material: 'Polycarbonate',
      finish: 'Pearl White',
      mechanism: 'Spring Return',
    },
    priceRange: { min: 95, max: 120, unit: 'per piece' },
    imageUrl: 'https://images.unsplash.com/photo-1563206767-5b18f218e8de?w=500',
  },
  {
    name: 'GM Modular Vivid 2-Way Switch - Glossy',
    category: 'SWITCHES_SOCKETS',
    brand: 'GM Modular',
    description: 'Affordable yet durable 2-way switch. Perfect for staircase lighting. Smooth toggle action with premium aesthetics.',
    specifications: {
      rating: '6A/10A, 240V',
      type: '2-Way',
      finish: 'Glossy Ivory',
      features: ['Staircase Lighting', 'Two-Point Control'],
    },
    priceRange: { min: 65, max: 85, unit: 'per piece' },
    imageUrl: 'https://images.unsplash.com/photo-1621857923996-c5c8d5cdc1f3?w=500',
  },

  // LED LIGHTING
  {
    name: 'Philips Stellar Bright 20W LED Batten',
    category: 'LIGHTING_FIXTURES',
    brand: 'Philips',
    description: 'Energy-efficient LED batten for homes and offices. Instant-on, flicker-free lighting with 5-year warranty. Replaces 40W tube light.',
    specifications: {
      wattage: '20W',
      lumens: '2000 lm',
      colorTemperature: '6500K Cool Daylight',
      lifespan: '25,000 hours',
      inputVoltage: '220-240V',
      warranty: '5 Years',
      features: ['Flicker-Free', 'Instant Start', 'Energy Star Rated'],
    },
    priceRange: { min: 280, max: 350, unit: 'per piece' },
    imageUrl: 'https://images.unsplash.com/photo-1567618898600-5c3c451b5260?w=500',
    popular: true,
  },
  {
    name: 'Syska 9W LED Bulb B22 Base',
    category: 'LIGHTING_FIXTURES',
    brand: 'Syska',
    description: 'High-efficiency LED bulb with standard B22 bayonet cap. Warm white light perfect for living rooms and bedrooms.',
    specifications: {
      wattage: '9W (Equivalent to 60W)',
      lumens: '900 lm',
      colorTemperature: '3000K Warm White',
      base: 'B22 (Bayonet)',
      lifespan: '15,000 hours',
      warranty: '2 Years',
    },
    priceRange: { min: 95, max: 120, unit: 'per piece' },
    imageUrl: 'https://images.unsplash.com/photo-1524484485831-a92ffc0de03f?w=500',
    popular: true,
  },
  {
    name: 'Havells Adonia 18W Ceiling LED Light',
    category: 'LIGHTING_FIXTURES',
    brand: 'Havells',
    description: 'Slim profile ceiling-mounted LED panel. Uniform light distribution with elegant design. Perfect for modern interiors.',
    specifications: {
      wattage: '18W',
      lumens: '1500 lm',
      colorTemperature: '4000K Natural White',
      size: '300mm x 300mm',
      mounting: 'Surface/Recessed',
      warranty: '3 Years',
    },
    priceRange: { min: 450, max: 550, unit: 'per piece' },
    imageUrl: 'https://images.unsplash.com/photo-1565084888279-aca607ecce0c?w=500',
  },
  {
    name: 'Crompton 15W Rechargeable Emergency LED Bulb',
    category: 'LIGHTING_FIXTURES',
    brand: 'Crompton',
    description: 'Smart emergency bulb with built-in battery. Works during power cuts. 4-hour backup time.',
    specifications: {
      wattage: '15W',
      lumens: '1200 lm',
      colorTemperature: '6500K',
      backup: '4 Hours',
      battery: 'Lithium-ion',
      charging: 'Auto-charge when power on',
    },
    priceRange: { min: 280, max: 350, unit: 'per piece' },
    imageUrl: 'https://images.unsplash.com/photo-1550985543-49bee3167284?w=500',
  },

  // MCBs & DISTRIBUTION
  {
    name: 'Schneider Easy9 32A C-Curve MCB - Single Pole',
    category: 'CIRCUIT_PROTECTION',
    brand: 'Schneider Electric',
    description: 'Miniature Circuit Breaker for reliable overload and short-circuit protection. C-curve ideal for residential loads. 10kA breaking capacity.',
    specifications: {
      rating: '32A',
      poles: 'Single Pole (SP)',
      curve: 'C-Curve',
      breakingCapacity: '10kA',
      standard: 'IS 60898-1',
      mounting: '35mm DIN Rail',
      trips: ['Thermal Overload', 'Magnetic Short Circuit'],
    },
    priceRange: { min: 180, max: 220, unit: 'per piece' },
    imageUrl: 'https://images.unsplash.com/photo-1621905252472-178bc76c2cda?w=500',
    popular: true,
  },
  {
    name: 'L&T 40A Double Pole MCB',
    category: 'CIRCUIT_PROTECTION',
    brand: 'L&T',
    description: 'Robust double-pole MCB for main supply protection. Suitable for single-phase distribution boards.',
    specifications: {
      rating: '40A',
      poles: 'Double Pole (DP)',
      curve: 'C-Curve',
      breakingCapacity: '6kA',
      standard: 'IS 60898-1',
      application: 'Main Incoming Supply',
    },
    priceRange: { min: 350, max: 420, unit: 'per piece' },
    imageUrl: 'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=500',
  },
  {
    name: 'Havells 4-Way Metal Distribution Board with MCB',
    category: 'CIRCUIT_PROTECTION',
    brand: 'Havells',
    description: 'Complete DB with 4 pre-installed MCBs and main switch. Powder-coated metal enclosure. Ready-to-install solution.',
    specifications: {
      ways: '4 + Main Switch',
      material: 'Metal (Powder Coated)',
      mcbsIncluded: true,
      mcbRatings: ['40A Main', '32A', '20A', '16A', '10A'],
      busbar: 'Copper',
      earthing: 'Earth Bar Included',
    },
    priceRange: { min: 1200, max: 1500, unit: 'per board' },
    imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500',
    popular: true,
  },
  {
    name: 'Siemens 30mA RCCB 4-Pole',
    category: 'CIRCUIT_PROTECTION',
    brand: 'Siemens',
    description: 'Residual Current Circuit Breaker for earth leakage protection. Protects against electric shocks. 30mA sensitivity.',
    specifications: {
      rating: '40A',
      poles: '4-Pole',
      sensitivity: '30mA',
      type: 'AC Type RCCB',
      standard: 'IS 12640',
      tripTime: '<30ms',
    },
    priceRange: { min: 850, max: 1050, unit: 'per piece' },
    imageUrl: 'https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500',
  },

  // FANS
  {
    name: 'Crompton Energion 1200mm Ceiling Fan',
    category: 'FANS_VENTILATION',
    brand: 'Crompton',
    description: 'Energy-efficient 5-star rated ceiling fan. High air delivery with low power consumption. Rust-free aluminum blades.',
    specifications: {
      sweepSize: '1200mm (48 inches)',
      power: '53W',
      airDelivery: '230 CMM',
      speed: '380 RPM',
      starRating: '5 Star',
      warranty: '2 Years',
      features: ['Rust-Free', 'High Speed', 'Low Noise'],
    },
    priceRange: { min: 1200, max: 1500, unit: 'per fan' },
    imageUrl: 'https://images.unsplash.com/photo-1622973536968-3ead9e780960?w=500',
    popular: true,
  },
  {
    name: 'Orient Electric Aeroquiet 1200mm BLDC Fan',
    category: 'FANS_VENTILATION',
    brand: 'Orient Electric',
    description: 'Premium BLDC motor fan with remote control. Ultra-silent operation. Energy savings up to 50%.',
    specifications: {
      sweepSize: '1200mm',
      motorType: 'BLDC (Brushless DC)',
      power: '28W',
      airDelivery: '220 CMM',
      speeds: '6-Speed Remote',
      starRating: '5 Star',
      warranty: '3 Years',
    },
    priceRange: { min: 2800, max: 3500, unit: 'per fan' },
    imageUrl: 'https://images.unsplash.com/photo-1580979914974-7eb24c2f79ca?w=500',
  },
  {
    name: 'Usha Mist Air Icy 400mm Exhaust Fan',
    category: 'FANS_VENTILATION',
    brand: 'Usha',
    description: 'High suction exhaust fan for kitchens and bathrooms. Removes smoke, odors, and moisture effectively.',
    specifications: {
      size: '400mm (16 inches)',
      application: 'Kitchen/Bathroom',
      airFlow: '1450 CMH',
      mounting: 'Wall/Window',
      blades: 'Aluminum',
      warranty: '2 Years',
    },
    priceRange: { min: 1800, max: 2200, unit: 'per fan' },
    imageUrl: 'https://images.unsplash.com/photo-1631889993959-41b4e9c6e3c5?w=500',
  },

  // WATER HEATERS & APPLIANCES
  {
    name: 'Racold Omnis Lux 15L Storage Water Heater',
    category: 'WATER_HEATING',
    brand: 'Racold',
    description: '15-liter vertical storage geyser with titanium-coated tank. 5-star energy rating. Perfect for bathrooms.',
    specifications: {
      capacity: '15 Liters',
      type: 'Storage (Vertical)',
      power: '2000W',
      tank: 'Titanium Coated Steel',
      heating: 'Fast Heating',
      safety: ['Thermostat', 'Thermal Cutout', 'Pressure Release Valve'],
      warranty: '5 Years Tank + 2 Years Element',
    },
    priceRange: { min: 7500, max: 9500, unit: 'per unit' },
    imageUrl: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=500',
    popular: true,
  },
  {
    name: 'Bajaj Majesty 3L Instant Water Heater',
    category: 'WATER_HEATING',
    brand: 'Bajaj',
    description: 'Compact instant geyser for small families. Glass-lined tank for durability. Rust and shock-proof body.',
    specifications: {
      capacity: '3 Liters',
      type: 'Instant',
      power: '3000W',
      tank: 'Glass-Lined',
      mounting: 'Wall-Mounted',
      warranty: '2 Years',
    },
    priceRange: { min: 4200, max: 5500, unit: 'per unit' },
    imageUrl: 'https://images.unsplash.com/photo-1589857574998-00af68a605ad?w=500',
  },

  // DOORBELLS & ACCESSORIES
  {
    name: 'Anchor Melodious Door Bell - Wired',
    category: 'DOORBELLS_ACCESSORIES',
    brand: 'Anchor',
    description: 'Musical doorbell with 16 melody options. Loud and clear sound. Easy installation.',
    specifications: {
      type: 'Wired',
      melodies: '16 Tunes',
      volumeControl: 'Yes',
      voltage: '220V AC',
      range: 'Wired Connection',
      warranty: '1 Year',
    },
    priceRange: { min: 180, max: 250, unit: 'per unit' },
    imageUrl: 'https://images.unsplash.com/photo-1558002038-1055907df827?w=500',
  },
  {
    name: 'Goldmedal Curve Plus Wireless Door Bell',
    category: 'DOORBELLS_ACCESSORIES',
    brand: 'Goldmedal',
    description: 'Wireless doorbell with 150m range. No wiring required. Battery-powered receiver and push button.',
    specifications: {
      type: 'Wireless',
      range: '150 meters',
      melodies: '36 Tunes',
      power: 'Battery (Receiver + Bell)',
      volume: '4 Levels',
      warranty: '1 Year',
    },
    priceRange: { min: 350, max: 450, unit: 'per unit' },
    imageUrl: 'https://images.unsplash.com/photo-1614359952614-9cd629c1e145?w=500',
  },
];

export const productCategories = [
  {
    id: 'ELECTRICAL_WIRING',
    name: 'Electrical Wiring',
    description: 'Cables, wires, conduits for home electrical installations',
    icon: '⚡',
  },
  {
    id: 'SWITCHES_SOCKETS',
    name: 'Switches & Sockets',
    description: 'Modular switches, sockets, dimmers, and accessories',
    icon: '🔌',
  },
  {
    id: 'LIGHTING_FIXTURES',
    name: 'LED Lighting',
    description: 'LED bulbs, battens, panels, and decorative lights',
    icon: '💡',
  },
  {
    id: 'CIRCUIT_PROTECTION',
    name: 'MCBs & Distribution',
    description: 'Circuit breakers, RCCBs, distribution boards, fuses',
    icon: '🔒',
  },
  {
    id: 'FANS_VENTILATION',
    name: 'Fans & Ventilation',
    description: 'Ceiling fans, exhaust fans, BLDC fans',
    icon: '🌀',
  },
  {
    id: 'WATER_HEATING',
    name: 'Water Heaters',
    description: 'Geysers, instant heaters, solar water heaters',
    icon: '🚿',
  },
  {
    id: 'DOORBELLS_ACCESSORIES',
    name: 'Doorbells & Accessories',
    description: 'Wired and wireless doorbells, home automation',
    icon: '🔔',
  },
];

export const trustedBrands = [
  { name: 'Polycab', logo: '🔵', tier: 'Premium' },
  { name: 'Havells', logo: '🔴', tier: 'Premium' },
  { name: 'Schneider Electric', logo: '🟢', tier: 'Premium' },
  { name: 'Legrand', logo: '⚫', tier: 'Premium' },
  { name: 'L&T', logo: '🟠', tier: 'Premium' },
  { name: 'Anchor', logo: '🟡', tier: 'Standard' },
  { name: 'GM Modular', logo: '🟣', tier: 'Standard' },
  { name: 'Goldmedal', logo: '🟤', tier: 'Standard' },
  { name: 'Philips', logo: '🔷', tier: 'Premium' },
  { name: 'Syska', logo: '🔶', tier: 'Standard' },
  { name: 'Crompton', logo: '🔺', tier: 'Standard' },
  { name: 'Orient Electric', logo: '🔻', tier: 'Standard' },
  { name: 'Usha', logo: '◾', tier: 'Standard' },
  { name: 'Bajaj', logo: '◼', tier: 'Standard' },
  { name: 'Siemens', logo: '⬛', tier: 'Premium' },
  { name: 'KEI', logo: '🟥', tier: 'Standard' },
  { name: 'Racold', logo: '🟦', tier: 'Premium' },
];
